In [1]:
import pandas as pd
import glob
import numpy as np

## Listing IDs

In [33]:
path = r'/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData' # use your path
all_files = glob.glob(path + "/listing_id_df*.csv")

li = []

for filename in all_files:
    df = pd.read_csv(filename, index_col=None, header=0)
    li.append(df)
    print(filename)
    
listing_ids_df = pd.concat(li, axis=0, ignore_index=True, sort=True)

listing_ids_df

/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/listing_id_df_072019.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/listing_id_df_072219.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/listing_id_df_071919.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/listing_id_df_072119.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/listing_id_df_071819.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/listing_id_df_071619.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/listing_id_df_071419.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/listing_id_df_070919.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/listing_id_df_071019.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/listing_id_df_071219.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/listing_id_df_071519.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/listing_id_df_071719.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/listing_id_df_071319.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/listing_id_df_071119.csv

           date  listingID                               title
0           NaN  722901675                                 NaN
1           NaN  721881161   Wood Table Number - Simple Design
2           NaN  721879701  Wood Table Number - Hexagon Design
3           NaN  701341356               Cake Topper-Dr. Seuss
4           NaN  687898920                Catalina PM-Set of 3
5           NaN  701344590            Fabric Garland-Dr. Seuss
6           NaN  701339360                     Banner-Dr.Seuss
7           NaN  701210678                 Party Hat-Dr. Seuss
8           NaN  701202082          Birthday Package-Dr. Seuss
9           NaN  702303569                  Wood Wedding Signs
10          NaN  700382982                  Gloria GM-ORB ONLY
11          NaN  700377146         Catalina PM - LANTERNS ONLY
12          NaN  706002567                   Chair Wreath-Hoop
13          NaN  691796412    Traveling from Miss to Mrs Signs
14          NaN  704569159           Chair Wreaths-Greenery(2)
15          NaN  690717354                  Gloria PM-ORB ONLY
16          NaN  703387331                       Wifey T Shirt
17          NaN  688465922                               Marie
18          NaN  688443618              Chair Wreaths-Greenery
19          NaN  685451744                     Catalina Bundle
20          NaN  693947901                           Gloria PM
21          NaN  680064082                            Florence
22          NaN  680069172                              Louise
23          NaN  680071910                                Ruby
24          NaN  680073964                               Helen
25          NaN  680077296                               Mabel
26          NaN  680079806                               Pearl
27          NaN  693930997                           Gloria GM
28          NaN  693933847                              Hattie
29          NaN  680082346                              Thelma
..          ...        ...                                 ...
393  2019-07-13  680085112                               Betty
394  2019-07-11  701341356               Cake Topper-Dr. Seuss
395  2019-07-11  687898920                Catalina PM-Set of 3
396  2019-07-11  701344590            Fabric Garland-Dr. Seuss
397  2019-07-11  701339360                     Banner-Dr.Seuss
398  2019-07-11  701210678                 Party Hat-Dr. Seuss
399  2019-07-11  701202082          Birthday Package-Dr. Seuss
400  2019-07-11  702303569                  Wood Wedding Signs
401  2019-07-11  700382982                  Gloria GM-ORB ONLY
402  2019-07-11  700377146         Catalina PM - LANTERNS ONLY
403  2019-07-11  706002567                   Chair Wreath-Hoop
404  2019-07-11  691796412    Traveling from Miss to Mrs Signs
405  2019-07-11  704569159           Chair Wreaths-Greenery(2)
406  2019-07-11  690717354                  Gloria PM-ORB ONLY
407  2019-07-11  703387331                       Wifey T Shirt
408  2019-07-11  688465922                               Marie
409  2019-07-11  688443618              Chair Wreaths-Greenery
410  2019-07-11  685451744                     Catalina Bundle
411  2019-07-11  693947901                           Gloria PM
412  2019-07-11  680064082                            Florence
413  2019-07-11  680069172                              Louise
414  2019-07-11  680071910                                Ruby
415  2019-07-11  680073964                               Helen
416  2019-07-11  680077296                               Mabel
417  2019-07-11  680079806                               Pearl
418  2019-07-11  693930997                           Gloria GM
419  2019-07-11  693933847                              Hattie
420  2019-07-11  680082346                              Thelma
421  2019-07-11  680084324                            Margaret
422  2019-07-11  680085112                               Betty

[423 rows x 3 columns]

In [34]:
listing_ids_df=listing_ids_df.rename(columns={'date':'record_date'})
listing_ids_df.head()

  record_date  listingID                               title
0         NaN  722901675                                 NaN
1         NaN  721881161   Wood Table Number - Simple Design
2         NaN  721879701  Wood Table Number - Hexagon Design
3         NaN  701341356               Cake Topper-Dr. Seuss
4         NaN  687898920                Catalina PM-Set of 3

In [35]:
listing_ids_df.to_csv(f"/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/Data/listing_id_cumm.csv",index=False,header=True,encoding="UTF-8")

## Listing Info

In [36]:
path = r'/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData' # use your path
all_files = glob.glob(path + "/listing_info_df*.csv")

li = []

for filename in all_files:
    df = pd.read_csv(filename, index_col=None, header=0)
    li.append(df)
    print(filename)
    
listing_info_df = pd.concat(li, axis=0, ignore_index=True, sort=True)

listing_info_df.head()

/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/listing_info_df_072219.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/listing_info_df_072019.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/listing_info_df_071919.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/listing_info_df_072119.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/listing_info_df_071819.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/listing_info_df_071419.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/listing_info_df_071619.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/listing_info_df_071219.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/listing_info_df_071019.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/listing_info_df_070919.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/listing_info_df_071719.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/listing_info_df_071519.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/listing_info_df_071119.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/listing_info_df_071319.csv

,customizable,date,dateCreated,dateExpires,digital,lastModified,listingID,listingTitle,state,url,variations
0,True,2019-07-22,72119,112119,False,72119,722901675,CUSTOM ORDER - BG,active,https://www.etsy.com/listing/722901675/custom-...,False
1,True,2019-07-22,71619,111719,False,71919,721881161,Table Numbers: Wood Table Number - Simple Design,active,https://www.etsy.com/listing/721881161/table-n...,True
2,True,2019-07-22,71619,111719,False,71919,721879701,Table Numbers: Wood Table Number - Hexagon Design,active,https://www.etsy.com/listing/721879701/table-n...,True
3,True,2019-07-22,70919,110919,False,71819,701341356,Birthday Cake Topper : Cake Topper-Dr. Seuss,active,https://www.etsy.com/listing/701341356/birthda...,True
4,True,2019-07-22,70419,110419,False,71019,687898920,Centerpiece - Set of 3 Lanterns & Candles : Ca...,active,https://www.etsy.com/listing/687898920/centerp...,False

In [29]:
listing_info_df=listing_info_df.rename(columns={'date':'record_date'})
listing_info_df.head()

,customizable,record_date,dateCreated,dateExpires,digital,lastModified,listingID,listingTitle,state,url,variations
0,True,2019-07-22,72119,112119,False,72119,722901675,CUSTOM ORDER - BG,active,https://www.etsy.com/listing/722901675/custom-...,False
1,True,2019-07-22,71619,111719,False,71919,721881161,Table Numbers: Wood Table Number - Simple Design,active,https://www.etsy.com/listing/721881161/table-n...,True
2,True,2019-07-22,71619,111719,False,71919,721879701,Table Numbers: Wood Table Number - Hexagon Design,active,https://www.etsy.com/listing/721879701/table-n...,True
3,True,2019-07-22,70919,110919,False,71819,701341356,Birthday Cake Topper : Cake Topper-Dr. Seuss,active,https://www.etsy.com/listing/701341356/birthda...,True
4,True,2019-07-22,70419,110419,False,71019,687898920,Centerpiece - Set of 3 Lanterns & Candles : Ca...,active,https://www.etsy.com/listing/687898920/centerp...,False

In [37]:
listing_info_df.to_csv(f"/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/Data/listing_info_cumm.csv",index=False,header=True,encoding="UTF-8")

## Listing Shipping

In [38]:
path = r'/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData' # use your path
all_files = glob.glob(path + "/listing_shipping)_df*.csv")

li = []

for filename in all_files:
    df = pd.read_csv(filename, index_col=None, header=0)
    li.append(df)
    print(filename)
    
listing_shipping_df = pd.concat(li, axis=0, ignore_index=True, sort=True)
listing_shipping_df=listing_shipping_df.rename(columns={'date':'record_date'})

listing_shipping_df.tail()

/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/listing_shipping)_df_072019.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/listing_shipping)_df_072219.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/listing_shipping)_df_071919.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/listing_shipping)_df_072119.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/listing_shipping)_df_071819.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/listing_shipping)_df_071619.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/listing_shipping)_df_071419.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/listing_shipping)_df_071019.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/listing_shipping)_df_070919.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/listing_shipping)_df_071219.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/listing_shipping)_df_071519.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/listing_shipping)_df_071719.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/listing_shipping)_df_071319.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/listing_shipping)_df_071119.csv

,record_date,itemDimensionalUnit,itemHeight,itemLength,itemWeight,itemWeightUnit,itemWidth,listingID,shippingTemplateID
418,2019-07-11,in,14.0,17.0,105.0,oz,14.0,693930997,7.219228e+10
419,2019-07-11,in,10.0,11.0,37.0,oz,11.0,693933847,7.219228e+10
420,2019-07-11,in,12.0,14.0,137.0,oz,14.0,680082346,7.219228e+10
421,2019-07-11,in,10.0,14.0,115.0,oz,12.0,680084324,7.219228e+10
422,2019-07-11,in,14.0,17.0,160.0,oz,14.0,680085112,7.219228e+10

In [39]:
listing_shipping_df.to_csv(f"/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/Data/listing_shipping_cumm.csv",index=False,header=True,encoding="UTF-8")

# Listing Images

In [41]:
path = r'/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData' # use your path
all_files = glob.glob(path + "/listing_images_df*.csv")

li = []

for filename in all_files:
    df = pd.read_csv(filename, index_col=None, header=0)
    li.append(df)
    print(filename)
    
df = pd.concat(li, axis=0, ignore_index=True, sort=True)
df=df.rename(columns={'date':'record_date'})

df.tail()

/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/listing_images_df_072119.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/listing_images_df_071819.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/listing_images_df_072219.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/listing_images_df_072019.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/listing_images_df_071919.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/listing_images_df_071719.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/listing_images_df_071519.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/listing_images_df_071119.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/listing_images_df_071319.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/listing_images_df_071419.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/listing_images_df_071619.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/listing_images_df_071219.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/listing_images_df_071019.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/listing_images_df_070919.csv

,record_date,listingID,listingImageID,listingImageRank,listingImageURL
2049,2019-07-09,680085112,1825640078,1,https://i.etsystatic.com/19804562/r/il/42f5b4/...
2050,2019-07-09,680085112,1873106081,2,https://i.etsystatic.com/19804562/r/il/4179e6/...
2051,2019-07-09,680085112,1825640228,3,https://i.etsystatic.com/19804562/r/il/c09da5/...
2052,2019-07-09,680085112,1873106445,4,https://i.etsystatic.com/19804562/r/il/335349/...
2053,2019-07-09,680085112,1873106127,5,https://i.etsystatic.com/19804562/r/il/6114a1/...

In [42]:
df.to_csv(f"/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/Data/listing_images_cumm.csv",index=False,header=True,encoding="UTF-8")

# Listing Categories

In [43]:
path = r'/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData' # use your path
all_files = glob.glob(path + "/listing_categorical_df*.csv")

li = []

for filename in all_files:
    df = pd.read_csv(filename, index_col=None, header=0)
    li.append(df)
    print(filename)
    
df = pd.concat(li, axis=0, ignore_index=True, sort=True)
df=df.rename(columns={'date':'record_date'})


df.tail()

/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/listing_categorical_df_071219.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/listing_categorical_df_070919.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/listing_categorical_df_071019.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/listing_categorical_df_071419.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/listing_categorical_df_071619.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/listing_categorical_df_071119.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/listing_categorical_df_071319.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/listing_categorical_df_071719.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/listing_categorical_df_071519.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/listing_categorical_df_071919.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/listing_categorical_df_072219.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/listing_categorical_df_072019.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/listing_categorical_df_071819.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/listing_categorical_df_072119.csv

     categoryID record_date  listingID  occasion  shopSectionID
418    68892264  2019-07-21  693930997       NaN       26512680
419    68892264  2019-07-21  693933847       NaN       26512680
420    68892264  2019-07-21  680082346       NaN       26512680
421    68892264  2019-07-21  680084324       NaN       26512680
422    68892264  2019-07-21  680085112       NaN       26512680

In [44]:
df.to_csv(f"/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/Data/listing_categories_cumm.csv",index=False,header=True,encoding="UTF-8")

# Listing Tags

In [45]:
# Error in original script which is why file name is stats df
path = r'/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData' # use your path
all_files = glob.glob(path + "/listing_stats_df*.csv")

li = []

for filename in all_files:
    df = pd.read_csv(filename, index_col=None, header=0)
    li.append(df)
    print(filename)
    
df = pd.concat(li, axis=0, ignore_index=True, sort=True)
df=df.rename(columns={'date':'record_date'})


df.tail()

/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/listing_stats_df_071319.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/listing_stats_df_071119.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/listing_stats_df_071519.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/listing_stats_df_071719.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/listing_stats_df_071019.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/listing_stats_df_070919.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/listing_stats_df_071219.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/listing_stats_df_071619.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/listing_stats_df_071419.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/listing_stats_df_071819.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/listing_stats_df_072119.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/listing_stats_df_071919.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/listing_stats_df_072019.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/listing_stats_df_072219.csv

     record_date  listingID                  tag
4686  2019-07-22  693930997  wedding decorations
4687  2019-07-22  693933847    anniversary party
4688  2019-07-22  680082346                decor
4689  2019-07-22  680084324         centerpieces
4690  2019-07-22  680085112          party decor

In [46]:
df.to_csv(f"/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/Data/listing_tags_cumm.csv",index=False,header=True,encoding="UTF-8")

# Production Time

In [47]:
path = r'/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData' # use your path
all_files = glob.glob(path + "/production_time_df*.csv")

li = []

for filename in all_files:
    df = pd.read_csv(filename, index_col=None, header=0)
    li.append(df)
    print(filename)
    
df = pd.concat(li, axis=0, ignore_index=True, sort=True)
df=df.rename(columns={'date':'record_date'})


df.tail()

/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/production_time_df_071619.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/production_time_df_071419.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/production_time_df_070919.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/production_time_df_071019.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/production_time_df_071219.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/production_time_df_071519.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/production_time_df_071719.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/production_time_df_071319.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/production_time_df_071119.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/production_time_df_072019.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/production_time_df_072219.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/production_time_df_071919.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/production_time_df_072119.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/production_time_df_071819.csv

    record_date  listingID  processingTimeMax  processingTimeMin
418  2019-07-18  693930997               15.0               10.0
419  2019-07-18  693933847               15.0               10.0
420  2019-07-18  680082346               15.0               10.0
421  2019-07-18  680084324               15.0               10.0
422  2019-07-18  680085112               15.0               10.0

In [48]:
df.to_csv(f"/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/Data/production_time_cumm.csv",index=False,header=True,encoding="UTF-8")

# Order Sold Items

In [50]:
path = r'/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData' # use your path
all_files = glob.glob(path + "/order_sold_items*.csv")

li = []

for filename in all_files:
    df = pd.read_csv(filename, index_col=None, header=0)
    li.append(df)
    print(filename)
    
df = pd.concat(li, axis=0, ignore_index=True, sort=True)
df['record_date']=''

df.tail()

/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/order_sold_items_071019.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/order_sold_items_070919.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/order_sold_items_071219.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/order_sold_items_071619.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/order_sold_items_071419.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/order_sold_items_071319.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/order_sold_items_071119.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/order_sold_items_071519.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/order_sold_items_071719.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/order_sold_items_071919.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/order_sold_items_072019.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/order_sold_items_072219.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/order_sold_items_071819.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/order_sold_items_072119.csv

,listingID,orderID,quantity,transactionID,variations,record_date
96,701341356,1471406642,1,1655782068,"Number of Letters/Flags:1-3,Personalization:ON...",
97,687898920,1467289834,2,1653796177,"Personalization:rehearsal dinner on August 9, ...",
98,702303569,1465581068,1,1651441691,"Stain Color:Dark,Size:8&quot; x 4&quot;,Person...",
99,687898920,1461258703,2,1629862796,NaN,
100,686163596,1441612324,1,1618371745,NaN,

In [51]:
df.to_csv(f"/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/Data/order_sold_items_cumm.csv",index=False,header=True,encoding="UTF-8")

# Buyers

In [52]:
path = r'/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData' # use your path
all_files = glob.glob(path + "/buyers_df*.csv")

li = []

for filename in all_files:
    df = pd.read_csv(filename, index_col=None, header=0)
    li.append(df)
    print(filename)
    
df = pd.concat(li, axis=0, ignore_index=True, sort=True)
df['record_date']=''


df.tail()

/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/buyers_df_072119.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/buyers_df_071819.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/buyers_df_072219.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/buyers_df_072019.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/buyers_df_071919.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/buyers_df_071719.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/buyers_df_071519.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/buyers_df_071119.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/buyers_df_071319.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/buyers_df_071419.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/buyers_df_071619.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/buyers_df_071219.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/buyers_df_071019.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/buyers_df_070919.csv

           buyerID firstName   lastName record_date
96      admoorhead    Alason   Moorhead
97         lmcq741     Loren        Day
98   marissaspacey   Marissa     Spacey
99    sshelburne12   Shannon  Shelburne
100       zvq52mlo    Amanda     Nelson

In [53]:
df.to_csv(f"/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/Data/buyers_cumm.csv",index=False,header=True,encoding="UTF-8")

# Shipping Addresses

In [56]:
path = r'/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData' # use your path
all_files = glob.glob(path + "/shipping_addresses*.csv")

li = []

for filename in all_files:
    df = pd.read_csv(filename, index_col=None, header=0)
    li.append(df)
    print(filename)
    
df = pd.concat(li, axis=0, ignore_index=True, sort=True)
df=df.rename(columns={'date':'record_date'})

df.head()

/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/shipping_addresses_df_071619.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/shipping_addresses_df_071419.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/shipping_addresses_df_071019.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/shipping_addresses_df_070919.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/shipping_addresses_df_071219.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/shipping_addresses_df_071519.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/shipping_addresses_df_071719.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/shipping_addresses_df_071319.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/shipping_addresses_df_071119.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/shipping_addresses_df_072019.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/shipping_addresses_df_072219.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/shipping_addresses_df_071919.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/shipping_addresses_df_072119.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/shipping_addresses_df_071819.csv

,buyerID,city,country,record_date,orderID,state,street1,street2,zipCode
0,dick0390,Stewartville,United States,NaN,1482734683,MN,806 Miller Lane SE,NaN,55976
1,cjoy123,Lodi,United States,NaN,1471997258,CA,505 Massarosa Lane,NaN,95240
2,admoorhead,Amarillo,United States,NaN,1471406642,TX,6903 Kingsbury Drive,NaN,79109
3,lmcq741,Norton,United States,NaN,1467289834,MA,78 Bay Rd,NaN,2766
4,marissaspacey,Bethpage,United States,NaN,1465581068,NY,3 Boone Street,NaN,11714

In [57]:
df.to_csv(f"/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/Data/shipping_addresses_cumm.csv",index=False,header=True,encoding="UTF-8")

# Orders

In [59]:
path = r'/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData' # use your path
all_files = glob.glob(path + "/orders_df*.csv")

li = []

for filename in all_files:
    df = pd.read_csv(filename, index_col=None, header=0)
    li.append(df)
    print(filename)
    
df = pd.concat(li, axis=0, ignore_index=True, sort=True)
df['record_date']=''

df.head()

/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/orders_df_071619.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/orders_df_071419.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/orders_df_070919.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/orders_df_071019.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/orders_df_071219.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/orders_df_071519.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/orders_df_071719.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/orders_df_071319.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/orders_df_071119.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/orders_df_072019.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/orders_df_072219.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/orders_df_071919.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/orders_df_072119.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/orders_df_071819.csv

,buyerID,orderDate,orderID,orderTime,orderURL,shipByDate,record_date
0,dick0390,07/09/19,1482734683,NaN,NaN,NaN,
1,cjoy123,07/04/19,1471997258,NaN,NaN,NaN,
2,admoorhead,07/02/19,1471406642,NaN,NaN,NaN,
3,lmcq741,06/21/19,1467289834,NaN,NaN,NaN,
4,marissaspacey,06/17/19,1465581068,NaN,NaN,NaN,
5,sshelburne12,05/15/19,1461258703,NaN,NaN,NaN,
6,zvq52mlo,04/19/19,1441612324,NaN,NaN,NaN,
7,dick0390,07/09/19,1482734683,10:52,https://www.etsy.com/your/orders/sold?ref=sell...,NaN,
8,cjoy123,07/04/19,1471997258,16:03,https://www.etsy.com/your/orders/sold?ref=sell...,NaN,
9,admoorhead,07/02/19,1471406642,22:36,https://www.etsy.com/your/orders/sold?ref=sell...,NaN,
10,lmcq741,06/21/19,1467289834,18:01,https://www.etsy.com/your/orders/sold?ref=sell...,NaN,
11,marissaspacey,06/17/19,1465581068,10:00,https://www.etsy.com/your/orders/sold?ref=sell...,NaN,
12,sshelburne12,05/15/19,1461258703,06:36,https://www.etsy.com/your/orders/sold?ref=sell...,NaN,
13,zvq52mlo,04/19/19,1441612324,12:04,https://www.etsy.com/your/orders/sold?ref=sell...,NaN,
14,dick0390,07/09/19,1482734683,10:52,https://www.etsy.com/your/orders/sold?ref=sell...,71619.0,
15,cjoy123,07/04/19,1471997258,16:03,https://www.etsy.com/your/orders/sold?ref=sell...,72519.0,
16,admoorhead,07/02/19,1471406642,NaN,NaN,NaN,
17,lmcq741,06/21/19,1467289834,NaN,NaN,NaN,
18,marissaspacey,06/17/19,1465581068,NaN,NaN,NaN,
19,sshelburne12,05/15/19,1461258703,NaN,NaN,NaN,
20,zvq52mlo,04/19/19,1441612324,NaN,NaN,NaN,
21,dick0390,07/09/19,1482734683,10:52,https://www.etsy.com/your/orders/sold?ref=sell...,71619.0,
22,cjoy123,07/04/19,1471997258,16:03,https://www.etsy.com/your/orders/sold?ref=sell...,72519.0,
23,admoorhead,07/02/19,1471406642,NaN,NaN,NaN,
24,lmcq741,06/21/19,1467289834,NaN,NaN,NaN,
25,marissaspacey,06/17/19,1465581068,NaN,NaN,NaN,
26,sshelburne12,05/15/19,1461258703,NaN,NaN,NaN,
27,zvq52mlo,04/19/19,1441612324,NaN,NaN,NaN,
28,dick0390,07/09/19,1482734683,NaN,NaN,NaN,
29,cjoy123,07/04/19,1471997258,NaN,NaN,NaN,
...,...,...,...,...,...,...,...
71,jessicaholder4,07/20/19,1487089393,NaN,NaN,NaN,
72,dick0390,07/09/19,1482734683,NaN,NaN,NaN,
73,cjoy123,07/04/19,1471997258,NaN,NaN,NaN,
74,admoorhead,07/02/19,1471406642,NaN,NaN,NaN,
75,lmcq741,06/21/19,1467289834,NaN,NaN,NaN,
76,marissaspacey,06/17/19,1465581068,NaN,NaN,NaN,
77,sshelburne12,05/15/19,1461258703,NaN,NaN,NaN,
78,zvq52mlo,04/19/19,1441612324,NaN,NaN,NaN,
79,dick0390,07/09/19,1482734683,NaN,NaN,NaN,
80,cjoy123,07/04/19,1471997258,NaN,NaN,NaN,
81,admoorhead,07/02/19,1471406642,NaN,NaN,NaN,
82,lmcq741,06/21/19,1467289834,NaN,NaN,NaN,
83,marissaspacey,06/17/19,1465581068,NaN,NaN,NaN,
84,sshelburne12,05/15/19,1461258703,NaN,NaN,NaN,
85,zvq52mlo,04/19/19,1441612324,NaN,NaN,NaN,
86,jessicaholder4,07/20/19,1487089393,NaN,NaN,NaN,
87,dick0390,07/09/19,1482734683,NaN,NaN,NaN,
88,cjoy123,07/04/19,1471997258,NaN,NaN,NaN,
89,admoorhead,07/02/19,1471406642,NaN,NaN,NaN,
90,lmcq741,06/21/19,1467289834,NaN,NaN,NaN,
91,marissaspacey,06/17/19,1465581068,NaN,NaN,NaN,
92,sshelburne12,05/15/19,1461258703,NaN,NaN,NaN,
93,zvq52mlo,04/19/19,1441612324,NaN,NaN,NaN,
94,dick0390,07/09/19,1482734683,NaN,NaN,NaN,
95,cjoy123,07/04/19,1471997258,NaN,NaN,NaN,
96,admoorhead,07/02/19,1471406642,NaN,NaN,NaN,
97,lmcq741,06/21/19,1467289834,NaN,NaN,NaN,
98,marissaspacey,06/17/19,1465581068,NaN,NaN,NaN,
99,sshelburne12,05/15/19,1461258703,NaN,NaN,NaN,
100,zvq52mlo,04/19/19,1441612324,NaN,NaN,NaN,

In [60]:
df.to_csv(f"/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/Data/orders_cumm.csv",index=False,header=True,encoding="UTF-8")

# Orders Shipped

In [61]:
path = r'/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData' # use your path
all_files = glob.glob(path + "/orders_shipped*.csv")

li = []

for filename in all_files:
    df = pd.read_csv(filename, index_col=None, header=0)
    li.append(df)
    print(filename)
    
df = pd.concat(li, axis=0, ignore_index=True, sort=True)
df['record_date']=''

df.head()

/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/orders_shipped_df_071619.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/orders_shipped_df_071419.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/orders_shipped_df_071019.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/orders_shipped_df_070919.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/orders_shipped_df_071219.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/orders_shipped_df_071519.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/orders_shipped_df_071719.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/orders_shipped_df_071319.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/orders_shipped_df_071119.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/orders_shipped_df_072019.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/orders_shipped_df_072219.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/orders_shipped_df_071919.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/orders_shipped_df_072119.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/orders_shipped_df_071819.csv

  dateShipped     orderID record_date
0    07/12/19  1482734683
1    07/12/19  1471997258
2    07/05/19  1471406642
3    07/05/19  1467289834
4    06/20/19  1465581068

In [62]:
df.to_csv(f"/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/Data/orders_shipped_cumm.csv",index=False,header=True,encoding="UTF-8")

# Order Payment

In [64]:
path = r'/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData' # use your path
all_files = glob.glob(path + "/order_payment_df*.csv")

li = []

for filename in all_files:
    df = pd.read_csv(filename, index_col=None, header=0)
    li.append(df)
    print(filename)
    
df = pd.concat(li, axis=0, ignore_index=True, sort=True)
df['record_date']=''

df.head()

/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/order_payment_df_071819.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/order_payment_df_072119.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/order_payment_df_071919.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/order_payment_df_072219.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/order_payment_df_072019.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/order_payment_df_071119.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/order_payment_df_071319.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/order_payment_df_071719.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/order_payment_df_071519.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/order_payment_df_071219.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/order_payment_df_071019.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/order_payment_df_070919.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/order_payment_df_071419.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/order_payment_df_071619.csv

,couponCode,discountAmount,fees,giftCard,orderID,orderNet,orderTotal,orderType,orderValue,paymentType,salesTax,shipping,shippingDiscount,record_date
0,NaN,0.0,0.75,No,1482734683,14.78,16.68,online,10.50,online_cc,0.00,5.03,0.0,
1,NaN,0.0,5.20,No,1471997258,159.76,164.96,online,99.98,online_cc,0.00,64.98,0.0,
2,NaN,0.0,0.77,No,1471406642,16.69,17.46,online,10.50,online_cc,1.33,5.63,0.0,
3,NaN,0.0,5.22,No,1467289834,160.34,165.56,online,99.98,online_cc,0.00,65.58,0.0,
4,NaN,0.0,0.65,No,1465581068,11.71,13.43,online,7.00,online_cc,0.00,5.36,0.0,

In [67]:
df.to_csv(f"/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/Data/order_payment_cumm.csv",index=False,header=True,encoding="UTF-8")

# Order Payment Adjustments

In [65]:
path = r'/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData' # use your path
all_files = glob.glob(path + "/order_payment_adjustments_df*.csv")

li = []

for filename in all_files:
    df = pd.read_csv(filename, index_col=None, header=0)
    li.append(df)
    print(filename)
    
df = pd.concat(li, axis=0, ignore_index=True, sort=True)
df['record_date']=''

df.head()

/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/order_payment_adjustments_df_071519.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/order_payment_adjustments_df_071719.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/order_payment_adjustments_df_071319.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/order_payment_adjustments_df_071119.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/order_payment_adjustments_df_071619.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/order_payment_adjustments_df_071419.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/order_payment_adjustments_df_070919.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/order_payment_adjustments_df_071019.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/order_payment_adjustments_df_071219.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/order_payment_adjustments_df_072119.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/order_payment_adjustments_df_071819.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/order_payment_adjustments_df_072019.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/order_payment_adjustments_df_072219.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/order_payment_adjustments_df_071919.csv

   adjustedFees  adjustedNet  adjustedTotal     orderID record_date
0           NaN          NaN            NaN  1482734683
1           NaN          NaN            NaN  1471997258
2           NaN          NaN            NaN  1471406642
3           NaN          NaN            NaN  1467289834
4           NaN          NaN            NaN  1465581068

In [66]:
df.to_csv(f"/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/Data/order_payment_adjustments_cumm.csv",index=False,header=True,encoding="UTF-8")

# Order Net

In [69]:
path = r'/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData' # use your path
all_files = glob.glob(path + "/OrderNet*.csv")

li = []

for filename in all_files:
    df = pd.read_csv(filename, index_col=None, header=0)
    li.append(df)
    print(filename)
    
df = pd.concat(li, axis=0, ignore_index=True, sort=True)


df.head()

/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/OrderNet_072219.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/OrderNet_072019.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/OrderNet_072119.csv

         date  orderNet
0  2019-07-23    180.06
1  2019-07-21    180.06
2  2019-07-22    180.06

In [70]:
df.to_csv(f"/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/Data/order_net_cumm.csv",index=False,header=True,encoding="UTF-8")

# Search Terms

In [72]:
path = r'/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData' # use your path
all_files = glob.glob(path + "/search_terms*.csv")

li = []

for filename in all_files:
    df = pd.read_csv(filename, index_col=None, header=0)
    li.append(df)
    print(filename)
    
df = pd.concat(li, axis=0, ignore_index=True, sort=True)
df=df.rename(columns={'date':'record_date'})


df.head()

/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/search_terms_071719.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/search_terms_071519.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/search_terms_071119.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/search_terms_071319.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/search_terms_071419.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/search_terms_071619.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/search_terms_071219.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/search_terms_070919.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/search_terms_071019.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/search_terms_072119.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/search_terms_071819.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/search_terms_072219.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/search_terms_072019.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/search_terms_071919.csv

   count record_date                           searchTerms
0      4  2019-07-17                   wedding centerpiece
1      1  2019-07-17  bridal shower centerpieces for table
2      1  2019-07-17                first birthday package
3      1  2019-07-17                               lantern
4      1  2019-07-17              centerpieces for wedding

In [73]:
df.to_csv(f"/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/Data/search_terms_cumm.csv",index=False,header=True,encoding="UTF-8")

# Open Orders

In [75]:
path = r'/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData' # use your path
all_files = glob.glob(path + "/open_orders*.csv")

li = []

for filename in all_files:
    df = pd.read_csv(filename, index_col=None, header=0)
    li.append(df)
    print(filename)
    
df = pd.concat(li, axis=0, ignore_index=True, sort=True)
df['record_date']=''


df.head()

/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/open_orders_df_071519.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/open_orders_df_071719.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/open_orders_df_071319.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/open_orders_df_071619.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/open_orders_df_071419.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/open_orders_df_072119.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/open_orders_df_071819.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/open_orders_df_072019.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/open_orders_df_072219.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/open_orders_df_071919.csv

,orderID,orderTime,orderURL,shipByDate,record_date
0,1482734683,10:52,https://www.etsy.com/your/orders/sold?ref=sell...,NaN,
1,1471997258,16:03,https://www.etsy.com/your/orders/sold?ref=sell...,NaN,
2,1467289834,18:01,https://www.etsy.com/your/orders/sold?ref=sell...,NaN,
3,1471406642,22:36,https://www.etsy.com/your/orders/sold?ref=sell...,NaN,
4,1465581068,10:00,https://www.etsy.com/your/orders/sold?ref=sell...,NaN,

In [76]:
df.to_csv(f"/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/Data/open_orders_cumm.csv",index=False,header=True,encoding="UTF-8")

# ERank Shop Stats

In [111]:
path = r'/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData' # use your path
all_files = glob.glob(path + "/erank_shop_stats_df*.csv")

li = []

for filename in all_files:
    df0 = pd.read_csv(filename, index_col=None, header=0)
    li.append(df0)
    print(filename)
    
df1 = pd.concat(li, axis=0, ignore_index=True, sort=True)


df1.head(10)

/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/erank_shop_stats_df_071619.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/erank_shop_stats_df_071419.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/erank_shop_stats_df_071519.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/erank_shop_stats_df_071719.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/erank_shop_stats_df_071919.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/erank_shop_stats_df_071819.csv

    date                   stat     value
0  71619            Total Sales         7
1  71619    Sales Rank (Global)   758,914
2  71619  Sales Rank (National)   394,347
3  71619               Shop Age  112 days
4  71619         Avg. Sales/Day      0.06
5  71619               Category  Weddings
6  71419            Total Sales         7
7  71419    Sales Rank (Global)   758,914
8  71419  Sales Rank (National)   394,347
9  71419               Shop Age  111 days

In [112]:
sales = []
record_date = []
salesRankWW = []
salesRankNAT = []
shopAge = []
avgSales = []
category = []

for index, item in df1.iterrows():
    if item[1]=="Total Sales":
        sales.append(item[2])
        record_date.append(item[0])
    if item[1]=="Sales Rank (Global)":
        salesRankWW.append(item[2])
    if item[1]=="Sales Rank (National)":
        salesRankNAT.append(item[2])
    if item[1]=="Shop Age":
        shopAge.append(item[2])
    if item[1]=="Avg. Sales/Day":
        avgSales.append(item[2])
    if item[1]=="Category":
        category.append(item[2])
        
df2 = pd.DataFrame({'record_date':record_date,
                  'avgSales':avgSales,
                  'category':category,
                  'salesRankWW':salesRankWW,
                  'salesRankNAT':salesRankNAT,
                  'shopAge':shopAge,
                  'sales':sales})

df2

   record_date avgSales  category salesRankWW salesRankNAT   shopAge sales
0        71619     0.06  Weddings     758,914      394,347  112 days     7
1        71419     0.06  Weddings     758,914      394,347  111 days     7
2        71519     0.06  Weddings     758,914      394,347  111 days     7
3        71719     0.06  Weddings     758,914      394,347  113 days     7
4        71919     0.07  Weddings     736,986      384,893  116 days     8
5        71819     0.06  Weddings     758,914      394,347  114 days     7

In [113]:
path = r'/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData' # use your path
all_files = glob.glob(path + "/eeerank_shop_stats_df*.csv")

li = []

for filename in all_files:
    df3 = pd.read_csv(filename, index_col=None, header=0)
    li.append(df3)
    print(filename)
    
df4 = pd.concat(li, axis=0, ignore_index=True, sort=True)
df4=df4.rename(columns={'date':'record_date'})

df4.head(10)

/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/eeerank_shop_stats_df_072119.csv

   avgSales  category record_date  sales salesRankNAT salesRankWW   shopAge
0      0.07  Weddings     7/21/19      8      384,893     736,986  118 days
1      0.07  Weddings     7/20/19      8      384,893     736,986  117 days
2      0.07  Weddings     7/22/19      8      384,893     736,986  119 days

In [114]:
df5 = pd.concat([df4,df2], ignore_index=True, sort=False)
df5

  avgSales  category record_date sales salesRankNAT salesRankWW   shopAge
0     0.07  Weddings     7/21/19     8      384,893     736,986  118 days
1     0.07  Weddings     7/20/19     8      384,893     736,986  117 days
2     0.07  Weddings     7/22/19     8      384,893     736,986  119 days
3     0.06  Weddings       71619     7      394,347     758,914  112 days
4     0.06  Weddings       71419     7      394,347     758,914  111 days
5     0.06  Weddings       71519     7      394,347     758,914  111 days
6     0.06  Weddings       71719     7      394,347     758,914  113 days
7     0.07  Weddings       71919     8      384,893     736,986  116 days
8     0.06  Weddings       71819     7      394,347     758,914  114 days

In [115]:
df5.to_csv(f"/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/Data/eRank_ShopStats_cumm.csv",index=False,header=True,encoding="UTF-8")

# Spotted On Etsy

In [117]:
path = r'/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData' # use your path
all_files = glob.glob(path + "/eRank_SpottedOnEtsy_*.csv")

li = []

for filename in all_files:
    df = pd.read_csv(filename, index_col=None, header=0)
    li.append(df)
    print(filename)
    
df = pd.concat(li, axis=0, ignore_index=True, sort=True)

df

/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/eRank_SpottedOnEtsy_071819.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/eRank_SpottedOnEtsy_072119.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/eRank_SpottedOnEtsy_071919.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/eRank_SpottedOnEtsy_072019.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/eRank_SpottedOnEtsy_072219.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/eRank_SpottedOnEtsy_071519.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/eRank_SpottedOnEtsy_071719.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/eRank_SpottedOnEtsy_071619.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/eRank_SpottedOnEtsy_071419.csv

,Unnamed: 0,listingID,page,position,rank,searchTerms,timestamp
0,0,701344590,2,28,76,fabric garland,9:12 AM Thursday 18th July
1,1,680064082,2,22,70,centerpieces for wedding,6:51 AM Thursday 18th July
2,2,680071910,1,38,38,centerpieces for bridal shower,6:51 AM Thursday 18th July
3,3,680079806,1,29,29,bridal shower centerpieces,6:19 AM Thursday 18th July
4,4,680079806,1,38,38,bridal shower centerpiece,6:19 AM Thursday 18th July
5,5,703387331,2,17,65,wifey tshirt,7:22 PM Thursday 18th July
6,6,700377146,2,21,69,Wood Lantern,7:37 PM Thursday 18th July
7,7,700377146,2,26,74,wood lanterns,7:37 PM Thursday 18th July
8,8,685451744,1,8,8,Wood Lantern,7:37 PM Thursday 18th July
9,9,685451744,1,9,9,wood lanterns,7:37 PM Thursday 18th July
10,0,701344590,2,35,83,fabric garland,9:05 AM Sunday 21st July
11,1,680064082,2,20,68,centerpieces for wedding,6:50 AM Sunday 21st July
12,2,680073964,2,36,84,centerpieces for bridal shower,6:50 AM Sunday 21st July
13,3,680071910,1,36,36,centerpieces for bridal shower,6:50 AM Sunday 21st July
14,4,680079806,1,30,30,bridal shower centerpieces,6:19 AM Sunday 21st July
15,5,680079806,1,38,38,bridal shower centerpiece,6:19 AM Sunday 21st July
16,6,703387331,2,16,64,wifey tshirt,6:53 PM Sunday 21st July
17,7,700377146,2,22,70,Wood Lantern,7:07 PM Sunday 21st July
18,8,700377146,2,27,75,wood lanterns,7:07 PM Sunday 21st July
19,9,685451744,1,7,7,Wood Lantern,7:07 PM Sunday 21st July
20,10,685451744,1,8,8,wood lanterns,7:07 PM Sunday 21st July
21,0,701344590,2,31,79,fabric garland,9:14 AM Friday 19th July
22,1,680064082,2,24,72,centerpieces for wedding,6:52 AM Friday 19th July
23,2,680073964,3,4,100,centerpieces for bridal shower,6:52 AM Friday 19th July
24,3,680071910,1,38,38,centerpieces for bridal shower,6:52 AM Friday 19th July
25,4,680079806,1,31,31,bridal shower centerpieces,6:21 AM Friday 19th July
26,5,680079806,1,39,39,bridal shower centerpiece,6:21 AM Friday 19th July
27,6,703387331,2,15,63,wifey tshirt,7:27 PM Friday 19th July
28,7,700377146,2,21,69,Wood Lantern,7:41 PM Friday 19th July
29,8,700377146,2,26,74,wood lanterns,7:41 PM Friday 19th July
...,...,...,...,...,...,...,...
68,4,685451744,1,14,14,centerpieces for bridal shower,6:49 AM Wednesday 17th July
69,5,685451744,2,6,54,bridal shower centerpieces,6:17 AM Wednesday 17th July
70,6,685451744,2,8,56,bridal shower centerpiece,6:17 AM Wednesday 17th July
71,7,680079806,1,29,29,bridal shower centerpieces,6:17 AM Wednesday 17th July
72,8,680079806,1,38,38,bridal shower centerpiece,6:17 AM Wednesday 17th July
73,9,703387331,2,16,64,wifey tshirt,7:14 PM Wednesday 17th July
74,10,700377146,2,21,69,Wood Lantern,7:29 PM Wednesday 17th July
75,11,700377146,2,26,74,wood lanterns,7:29 PM Wednesday 17th July
76,12,685451744,1,7,7,Wood Lantern,7:29 PM Wednesday 17th July
77,13,685451744,1,8,8,wood lanterns,7:29 PM Wednesday 17th July
78,0,700382982,2,45,93,bridal shower centerpieces,6:17 AM Tuesday 16th July
79,1,700377146,1,12,12,lanterns centerpieces for wedding,12:03 PM Tuesday 16th July
80,2,680064082,2,24,72,centerpieces for wedding,6:48 AM Tuesday 16th July
81,3,680071910,2,8,56,centerpieces for bridal shower,6:48 AM Tuesday 16th July
82,4,685451744,1,16,16,centerpieces for bridal shower,6:48 AM Tuesday 16th July
83,5,685451744,2,6,54,bridal shower centerpieces,6:17 AM Tuesday 16th July
84,6,685451744,2,8,56,bridal shower centerpiece,6:17 AM Tuesday 16th July
85,7,680079806,1,33,33,bridal shower centerpieces,6:17 AM Tuesday 16th July
86,8,680079806,1,42,42,bridal shower centerpiece,6:17 AM Tuesday 16th July
87,9,703387331,2,20,68,wifey tshirt,7:02 PM Tuesday 16th July
88,0,700382982,2,45,93,bridal shower centerpieces,6:15 AM Sunday 14th July
89,1,700377146,1,12,12,lanterns centerpieces for wedding,11:53 AM Sunday 14th July
90,2,680064082,1,31,31,Party Centerpiece,2:43 PM Sunday 14th July
91,3,680071910,2,8,56,centerpieces for bridal shower,6:46 AM Sunday 14th July
92,4,685451744,1,16,16,centerpieces for bridal shower,6:46 AM Sunday 14th July
93,5,685451744,2,7,55,bridal shower centerpieces,6:15 AM Sunday 14th July
94,6,685451744,2,9,57,bridal shower centerpiece,6:15 AM Sunday 14th July
95,7,680079806,1,32,32,bridal shower centerpieces,6:15 AM Sunday 14th July
96,8,680079806,1,40,40,bridal shower centerpiece,6:15 AM Sunday 14th July
97,9,703387331,2,16,64,wifey tshirt,7:32 PM Sunday 14th July

In [118]:
df.columns

Index(['Unnamed: 0', 'listingID', 'page', 'position', 'rank', 'searchTerms',
       'timestamp'],
      dtype='object')

In [119]:
df=df[['listingID', 'page', 'position', 'rank', 'searchTerms',
       'timestamp']]
df

,listingID,page,position,rank,searchTerms,timestamp
0,701344590,2,28,76,fabric garland,9:12 AM Thursday 18th July
1,680064082,2,22,70,centerpieces for wedding,6:51 AM Thursday 18th July
2,680071910,1,38,38,centerpieces for bridal shower,6:51 AM Thursday 18th July
3,680079806,1,29,29,bridal shower centerpieces,6:19 AM Thursday 18th July
4,680079806,1,38,38,bridal shower centerpiece,6:19 AM Thursday 18th July
5,703387331,2,17,65,wifey tshirt,7:22 PM Thursday 18th July
6,700377146,2,21,69,Wood Lantern,7:37 PM Thursday 18th July
7,700377146,2,26,74,wood lanterns,7:37 PM Thursday 18th July
8,685451744,1,8,8,Wood Lantern,7:37 PM Thursday 18th July
9,685451744,1,9,9,wood lanterns,7:37 PM Thursday 18th July
10,701344590,2,35,83,fabric garland,9:05 AM Sunday 21st July
11,680064082,2,20,68,centerpieces for wedding,6:50 AM Sunday 21st July
12,680073964,2,36,84,centerpieces for bridal shower,6:50 AM Sunday 21st July
13,680071910,1,36,36,centerpieces for bridal shower,6:50 AM Sunday 21st July
14,680079806,1,30,30,bridal shower centerpieces,6:19 AM Sunday 21st July
15,680079806,1,38,38,bridal shower centerpiece,6:19 AM Sunday 21st July
16,703387331,2,16,64,wifey tshirt,6:53 PM Sunday 21st July
17,700377146,2,22,70,Wood Lantern,7:07 PM Sunday 21st July
18,700377146,2,27,75,wood lanterns,7:07 PM Sunday 21st July
19,685451744,1,7,7,Wood Lantern,7:07 PM Sunday 21st July
20,685451744,1,8,8,wood lanterns,7:07 PM Sunday 21st July
21,701344590,2,31,79,fabric garland,9:14 AM Friday 19th July
22,680064082,2,24,72,centerpieces for wedding,6:52 AM Friday 19th July
23,680073964,3,4,100,centerpieces for bridal shower,6:52 AM Friday 19th July
24,680071910,1,38,38,centerpieces for bridal shower,6:52 AM Friday 19th July
25,680079806,1,31,31,bridal shower centerpieces,6:21 AM Friday 19th July
26,680079806,1,39,39,bridal shower centerpiece,6:21 AM Friday 19th July
27,703387331,2,15,63,wifey tshirt,7:27 PM Friday 19th July
28,700377146,2,21,69,Wood Lantern,7:41 PM Friday 19th July
29,700377146,2,26,74,wood lanterns,7:41 PM Friday 19th July
...,...,...,...,...,...,...
68,685451744,1,14,14,centerpieces for bridal shower,6:49 AM Wednesday 17th July
69,685451744,2,6,54,bridal shower centerpieces,6:17 AM Wednesday 17th July
70,685451744,2,8,56,bridal shower centerpiece,6:17 AM Wednesday 17th July
71,680079806,1,29,29,bridal shower centerpieces,6:17 AM Wednesday 17th July
72,680079806,1,38,38,bridal shower centerpiece,6:17 AM Wednesday 17th July
73,703387331,2,16,64,wifey tshirt,7:14 PM Wednesday 17th July
74,700377146,2,21,69,Wood Lantern,7:29 PM Wednesday 17th July
75,700377146,2,26,74,wood lanterns,7:29 PM Wednesday 17th July
76,685451744,1,7,7,Wood Lantern,7:29 PM Wednesday 17th July
77,685451744,1,8,8,wood lanterns,7:29 PM Wednesday 17th July
78,700382982,2,45,93,bridal shower centerpieces,6:17 AM Tuesday 16th July
79,700377146,1,12,12,lanterns centerpieces for wedding,12:03 PM Tuesday 16th July
80,680064082,2,24,72,centerpieces for wedding,6:48 AM Tuesday 16th July
81,680071910,2,8,56,centerpieces for bridal shower,6:48 AM Tuesday 16th July
82,685451744,1,16,16,centerpieces for bridal shower,6:48 AM Tuesday 16th July
83,685451744,2,6,54,bridal shower centerpieces,6:17 AM Tuesday 16th July
84,685451744,2,8,56,bridal shower centerpiece,6:17 AM Tuesday 16th July
85,680079806,1,33,33,bridal shower centerpieces,6:17 AM Tuesday 16th July
86,680079806,1,42,42,bridal shower centerpiece,6:17 AM Tuesday 16th July
87,703387331,2,20,68,wifey tshirt,7:02 PM Tuesday 16th July
88,700382982,2,45,93,bridal shower centerpieces,6:15 AM Sunday 14th July
89,700377146,1,12,12,lanterns centerpieces for wedding,11:53 AM Sunday 14th July
90,680064082,1,31,31,Party Centerpiece,2:43 PM Sunday 14th July
91,680071910,2,8,56,centerpieces for bridal shower,6:46 AM Sunday 14th July
92,685451744,1,16,16,centerpieces for bridal shower,6:46 AM Sunday 14th July
93,685451744,2,7,55,bridal shower centerpieces,6:15 AM Sunday 14th July
94,685451744,2,9,57,bridal shower centerpiece,6:15 AM Sunday 14th July
95,680079806,1,32,32,bridal shower centerpieces,6:15 AM Sunday 14th July
96,680079806,1,40,40,bridal shower centerpiece,6:15 AM Sunday 14th July
97,703387331,2,16,64,wifey tshirt,7:32 PM Sunday 14th July

In [120]:
df.to_csv(f"/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/Data/eRank_SpottedOnEtsy_cumm.csv",index=False,header=True,encoding="UTF-8")

# Sold Orders

In [123]:
path = r'/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/ShopDataCSV' # use your path
all_files = glob.glob(path + "/EtsySoldOrders*.csv")

li = []

for filename in all_files:
    df = pd.read_csv(filename, index_col=None, header=0)
    li.append(df)
    print(filename)
    
df = pd.concat(li, axis=0, ignore_index=True, sort=True)

df

/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/ShopDataCSV/EtsySoldOrders071919.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/ShopDataCSV/EtsySoldOrders072019.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/ShopDataCSV/EtsySoldOrders072219.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/ShopDataCSV/EtsySoldOrders071819.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/ShopDataCSV/EtsySoldOrders072119.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/ShopDataCSV/EtsySoldOrders071019.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/ShopDataCSV/EtsySoldOrders070919.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/ShopDataCSV/EtsySoldOrders071219.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/ShopDataCSV/EtsySoldOrders071619.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/ShopDataCSV/EtsySoldOrders071419.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/ShopDataCSV/EtsySoldOrders071319.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/ShopDataCSV/EtsySoldOrders071119.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/ShopDataCSV/EtsySoldOrders071519.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/ShopDataCSV/EtsySoldOrders071719.csv

,Adjusted Card Processing Fees,Adjusted Net Order Amount,Adjusted Order Total,Buyer,Buyer User ID,Card Processing Fees,Coupon Code,Coupon Details,Currency,Date Shipped,...,Sales Tax,Ship City,Ship Country,Ship State,Ship Zipcode,Shipping,Shipping Discount,Status,Street 1,Street 2
0,NaN,NaN,NaN,Kadi Davis,dick0390,0.75,NaN,NaN,USD,07/12/19,...,0.00,Stewartville,United States,MN,55976,5.03,0.0,NaN,806 Miller Lane SE,NaN
1,NaN,NaN,NaN,Cierra Abdollahzadeh,cjoy123,5.20,NaN,NaN,USD,07/12/19,...,0.00,Lodi,United States,CA,95240,64.98,0.0,NaN,505 Massarosa Lane,NaN
2,NaN,NaN,NaN,Alason Moorhead,admoorhead,0.77,NaN,NaN,USD,07/05/19,...,1.33,Amarillo,United States,TX,79109,5.63,0.0,NaN,6903 Kingsbury Drive,NaN
3,NaN,NaN,NaN,Loren Day,lmcq741,5.22,NaN,NaN,USD,07/05/19,...,0.00,Norton,United States,MA,2766,65.58,0.0,NaN,78 Bay Rd,NaN
4,NaN,NaN,NaN,Marissa Spacey,marissaspacey,0.65,NaN,NaN,USD,06/20/19,...,0.00,Bethpage,United States,NY,11714,5.36,0.0,NaN,3 Boone Street,NaN
5,NaN,NaN,NaN,Shannon Shelburne,sshelburne12,4.04,NaN,NaN,USD,05/28/19,...,0.00,Midland,United States,VA,22728,39.36,0.0,NaN,2287 Beaver Dam Rd,NaN
6,NaN,NaN,NaN,Amanda Nelson,zvq52mlo,3.52,NaN,NaN,USD,04/28/19,...,0.00,CHICAGO,United States,IL,60631,26.98,0.0,NaN,6146 N Avondale Ave,NaN
7,NaN,NaN,NaN,Jessica Holder,jessicaholder4,0.28,NaN,NaN,USD,NaN,...,0.00,Dallas,United States,TX,75244,0.00,0.0,NaN,3985 Crown Shore Dr,NaN
8,NaN,NaN,NaN,Kadi Davis,dick0390,0.75,NaN,NaN,USD,07/12/19,...,0.00,Stewartville,United States,MN,55976,5.03,0.0,NaN,806 Miller Lane SE,NaN
9,NaN,NaN,NaN,Cierra Abdollahzadeh,cjoy123,5.20,NaN,NaN,USD,07/12/19,...,0.00,Lodi,United States,CA,95240,64.98,0.0,NaN,505 Massarosa Lane,NaN
10,NaN,NaN,NaN,Alason Moorhead,admoorhead,0.77,NaN,NaN,USD,07/05/19,...,1.33,Amarillo,United States,TX,79109,5.63,0.0,NaN,6903 Kingsbury Drive,NaN
11,NaN,NaN,NaN,Loren Day,lmcq741,5.22,NaN,NaN,USD,07/05/19,...,0.00,Norton,United States,MA,2766,65.58,0.0,NaN,78 Bay Rd,NaN
12,NaN,NaN,NaN,Marissa Spacey,marissaspacey,0.65,NaN,NaN,USD,06/20/19,...,0.00,Bethpage,United States,NY,11714,5.36,0.0,NaN,3 Boone Street,NaN
13,NaN,NaN,NaN,Shannon Shelburne,sshelburne12,4.04,NaN,NaN,USD,05/28/19,...,0.00,Midland,United States,VA,22728,39.36,0.0,NaN,2287 Beaver Dam Rd,NaN
14,NaN,NaN,NaN,Amanda Nelson,zvq52mlo,3.52,NaN,NaN,USD,04/28/19,...,0.00,CHICAGO,United States,IL,60631,26.98,0.0,NaN,6146 N Avondale Ave,NaN
15,NaN,NaN,NaN,Jessica Holder,jessicaholder4,0.28,NaN,NaN,USD,07/21/19,...,0.00,Dallas,United States,TX,75244,0.00,0.0,NaN,3985 Crown Shore Dr,NaN
16,NaN,NaN,NaN,Kadi Davis,dick0390,0.75,NaN,NaN,USD,07/12/19,...,0.00,Stewartville,United States,MN,55976,5.03,0.0,NaN,806 Miller Lane SE,NaN
17,NaN,NaN,NaN,Cierra Abdollahzadeh,cjoy123,5.20,NaN,NaN,USD,07/12/19,...,0.00,Lodi,United States,CA,95240,64.98,0.0,NaN,505 Massarosa Lane,NaN
18,NaN,NaN,NaN,Alason Moorhead,admoorhead,0.77,NaN,NaN,USD,07/05/19,...,1.33,Amarillo,United States,TX,79109,5.63,0.0,NaN,6903 Kingsbury Drive,NaN
19,NaN,NaN,NaN,Loren Day,lmcq741,5.22,NaN,NaN,USD,07/05/19,...,0.00,Norton,United States,MA,2766,65.58,0.0,NaN,78 Bay Rd,NaN
20,NaN,NaN,NaN,Marissa Spacey,marissaspacey,0.65,NaN,NaN,USD,06/20/19,...,0.00,Bethpage,United States,NY,11714,5.36,0.0,NaN,3 Boone Street,NaN
21,NaN,NaN,NaN,Shannon Shelburne,sshelburne12,4.04,NaN,NaN,USD,05/28/19,...,0.00,Midland,United States,VA,22728,39.36,0.0,NaN,2287 Beaver Dam Rd,NaN
22,NaN,NaN,NaN,Amanda Nelson,zvq52mlo,3.52,NaN,NaN,USD,04/28/19,...,0.00,CHICAGO,United States,IL,60631,26.98,0.0,NaN,6146 N Avondale Ave,NaN
23,NaN,NaN,NaN,Kadi Davis,dick0390,0.75,NaN,NaN,USD,07/12/19,...,0.00,Stewartville,United States,MN,55976,5.03,0.0,NaN,806 Miller Lane SE,NaN
24,NaN,NaN,NaN,Cierra Abdollahzadeh,cjoy123,5.20,NaN,NaN,USD,07/12/19,...,0.00,Lodi,United States,CA,95240,64.98,0.0,NaN,505 Massarosa Lane,NaN
25,NaN,NaN,NaN,Alason Moorhead,admoorhead,0.77,NaN,NaN,USD,07/05/19,...,1.33,Amarillo,United States,TX,79109,5.63,0.0,NaN,6903 Kingsbury Drive,NaN
26,NaN,NaN,NaN,Loren Day,lmcq741,5.22,NaN,NaN,USD,07/05/19,...,0.00,Norton,United States,MA,2766,65.58,0.0,NaN,78 Bay Rd,NaN
27,NaN,NaN,NaN,Marissa Spacey,marissaspacey,0.65,NaN,NaN,USD,06/20/19,...,0.00,Bethpage,United States,NY,11714,5.36,0.0,NaN,3 Boone Street,NaN
28,NaN,NaN,NaN,Shannon Shelburne,sshelburne12,4.04,NaN,NaN,USD,05/28/19,...,0.00,Midland,United States,VA,22728,39.36,0.0,NaN,2287 Beaver Dam Rd,NaN
29,NaN,NaN,NaN,Amanda Nelson,zvq52mlo,3.52,NaN,NaN,USD,04/28/19,...,0.00,CHICAGO,United States,IL,60631,26.98,0.0,NaN,6146 N Avondale Ave,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71,NaN,NaN,NaN,Shannon Shelburne,sshelburne12,4.04,NaN,NaN,USD,05/28/19,...,0.00,Midland,United States,VA,22728,39.36,0.0,NaN,2287 Beaver Dam Rd,NaN
72,NaN,NaN,NaN,Amanda Nelson,zvq52mlo,3.52,NaN,NaN,USD,04/28/19,...,0.00,CHICAGO,United States,IL,60631,26.98,0.0,NaN,6146 N Avondale Ave,NaN
73,NaN,NaN,NaN,Kadi Davis,dick0390,0.75,NaN,NaN,USD,07/12/19,...,0.00,Stewartville,United States,MN,55976,5.03,0.0,NaN,806 Miller Lane SE,NaN
74,NaN,NaN,NaN,Cierra Abdollahzadeh,cjoy123,5.20,NaN,NaN,USD,07/12/19,...,0.00,Lodi,United States,CA,95240,64.98,0.0,NaN,505 Massarosa Lane,NaN
75,NaN,NaN,NaN,Alason Moorhead,admoorhead,0.77,NaN,NaN,USD,07/05/19,...,1.33,Amarillo,United States,TX,79109,5.63,0.0,NaN,6903 Kingsbury Drive,NaN
76,NaN,NaN,NaN,Loren Day,lmcq741,5.22,NaN,NaN,USD,07/05/19,...,0.00,Norton,United States,MA,2766,65.58,0.0,NaN,78 Bay Rd,NaN
77,NaN,NaN,NaN,Marissa Spacey,marissaspacey,0.65,NaN,NaN,USD,06/20/19,...,0.00,Bethpage,United States,NY,11714,5.36,0.0,NaN,3 Boone Street,NaN
78,NaN,NaN,NaN,Shannon Shelburne,sshelburne12,4.04,NaN,NaN,USD,05/28/19,...,0.00,Midland,United States,VA,22728,39.36,0.0,NaN,2287 Beaver Dam Rd,NaN
79,NaN,NaN,NaN,Amanda Nelson,zvq52mlo,3.52,NaN,NaN,USD,04/28/19,...,0.00,CHICAGO,United States,IL,60631,26.98,0.0,NaN,6146 N Avondale Ave,NaN
80,NaN,NaN,NaN,Kadi Davis,dick0390,0.75,NaN,NaN,USD,NaN,...,0.00,Stewartville,United States,MN,55976,5.03,0.0,NaN,806 Miller Lane SE,NaN
81,NaN,NaN,NaN,Cierra Abdollahzadeh,cjoy123,5.20,NaN,NaN,USD,NaN,...,0.00,Lodi,United States,CA,95240,64.98,0.0,NaN,505 Massarosa Lane,NaN
82,NaN,NaN,NaN,Alason Moorhead,admoorhead,0.77,NaN,NaN,USD,07/05/19,...,1.33,Amarillo,United States,TX,79109,5.63,0.0,NaN,6903 Kingsbury Drive,NaN
83,NaN,NaN,NaN,Loren Day,lmcq741,5.22,NaN,NaN,USD,07/05/19,...,0.00,Norton,United States,MA,2766,65.58,0.0,NaN,78 Bay Rd,NaN
84,NaN,NaN,NaN,Marissa Spacey,marissaspacey,0.65,NaN,NaN,USD,06/20/19,...,0.00,Bethpage,United States,NY,11714,5.36,0.0,NaN,3 Boone Street,NaN
85,NaN,NaN,NaN,Shannon Shelburne,sshelburne12,4.04,NaN,NaN,USD,05/28/19,...,0.00,Midland,United States,VA,22728,39.36,0.0,NaN,2287 Beaver Dam Rd,NaN
86,NaN,NaN,NaN,Amanda Nelson,zvq52mlo,3.52,NaN,NaN,USD,04/28/19,...,0.00,CHICAGO,United States,IL,60631,26.98,0.0,NaN,6146 N Avondale Ave,NaN
87,NaN,NaN,NaN,Kadi Davis,dick0390,0.75,NaN,NaN,USD,07/12/19,...,0.00,Stewartville,United States,MN,55976,5.03,0.0,NaN,806 Miller Lane SE,NaN
88,NaN,NaN,NaN,Cierra Abdollahzadeh,cjoy123,5.20,NaN,NaN,USD,07/12/19,...,0.00,Lodi,United States,CA,95240,64.98,0.0,NaN,505 Massarosa Lane,NaN
89,NaN,NaN,NaN,Alason Moorhead,admoorhead,0.77,NaN,NaN,USD,07/05/19,...,1.33,Amarillo,United States,TX,79109,5.63,0.0,NaN,6903 Kingsbury Drive,NaN
90,NaN,NaN,NaN,Loren Day,lmcq741,5.22,NaN,NaN,USD,07/05/19,...,0.00,Norton,United States,MA,2766,65.58,0.0,NaN,78 Bay Rd,NaN
91,NaN,NaN,NaN,Marissa Spacey,marissaspacey,0.65,NaN,NaN,USD,06/20/19,...,0.00,Bethpage,United States,NY,11714,5.36,0.0,NaN,3 Boone Street,NaN
92,NaN,NaN,NaN,Shannon Shelburne,sshelburne12,4.04,NaN,NaN,USD,05/28/19,...,0.00,Midland,United States,VA,22728,39.36,0.0,NaN,2287 Beaver Dam Rd,NaN
93,NaN,NaN,NaN,Amanda Nelson,zvq52mlo,3.52,NaN,NaN,USD,04/28/19,...,0.00,CHICAGO,United States,IL,60631,26.98,0.0,NaN,6146 N Avondale Ave,NaN
94,NaN,NaN,NaN,Kadi Davis,dick0390,0.75,NaN,NaN,USD,07/12/19,...,0.00,Stewartville,United States,MN,55976,5.03,0.0,NaN,806 Miller Lane SE,NaN
95,NaN,NaN,NaN,Cierra Abdollahzadeh,cjoy123,5.20,NaN,NaN,USD,07/12/19,...,0.00,Lodi,United States,CA,95240,64.98,0.0,NaN,505 Massarosa Lane,NaN
96,NaN,NaN,NaN,Alason Moorhead,admoorhead,0.77,NaN,NaN,USD,07/05/19,...,1.33,Amarillo,United States,TX,79109,5.63,0.0,NaN,6903 Kingsbury Drive,NaN
97,NaN,NaN,NaN,Loren Day,lmcq741,5.22,NaN,NaN,USD,07/05/19,...,0.00,Norton,United States,MA,2766,65.58,0.0,NaN,78 Bay Rd,NaN
98,NaN,NaN,NaN,Marissa Spacey,marissaspacey,0.65,NaN,NaN,USD,06/20/19,...,0.00,Bethpage,United States,NY,11714,5.36,0.0,NaN,3 Boone Street,NaN
99,NaN,NaN,NaN,Shannon Shelburne,sshelburne12,4.04,NaN,NaN,USD,05/28/19,...,0.00,Midland,United States,VA,22728,39.36,0.0,NaN,2287 Beaver Dam Rd,NaN
100,NaN,NaN,NaN,Amanda Nelson,zvq52mlo,3.52,NaN,NaN,USD,04/28/19,...,0.00,CHICAGO,United States,IL,60631,26.98,0.0,NaN,6146 N Avondale Ave,NaN

In [124]:
df.to_csv(f"/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/Data/EtsySoldOrders_cumm.csv",index=False,header=True,encoding="UTF-8")

# Sold Order Items

In [126]:
path = r'/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/ShopDataCSV' # use your path
all_files = glob.glob(path + "/EtsySoldOrderItems*.csv")

li = []

for filename in all_files:
    df = pd.read_csv(filename, index_col=None, header=0)
    li.append(df)
    print(filename)
    
df = pd.concat(li, axis=0, ignore_index=True, sort=True)

df

/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/ShopDataCSV/EtsySoldOrderItems071719.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/ShopDataCSV/EtsySoldOrderItems071519.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/ShopDataCSV/EtsySoldOrderItems071119.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/ShopDataCSV/EtsySoldOrderItems071319.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/ShopDataCSV/EtsySoldOrderItems071419.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/ShopDataCSV/EtsySoldOrderItems071619.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/ShopDataCSV/EtsySoldOrderItems071219.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/ShopDataCSV/EtsySoldOrderItems071019.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/ShopDataCSV/EtsySoldOrderItems070919.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/ShopDataCSV/EtsySoldOrderItems072119.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/ShopDataCSV/EtsySoldOrderItems071819.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/ShopDataCSV/EtsySoldOrderItems072219.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/ShopDataCSV/EtsySoldOrderItems072019.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/ShopDataCSV/EtsySoldOrderItems071919.csv

,Buyer,Coupon Code,Coupon Details,Currency,Date Paid,Date Shipped,Discount Amount,InPerson Discount,InPerson Location,Item Name,...,Ship Address2,Ship City,Ship Country,Ship Name,Ship State,Ship Zipcode,Shipping Discount,Transaction ID,VAT Paid by Buyer,Variations
0,Kadi Davis (dick0390),NaN,NaN,USD,07/09/2019,07/12/2019,0.0,NaN,NaN,"Cake Topper, Dr. Seuss, First Birthday, Second...",...,NaN,Stewartville,United States,Kadi Davis,MN,55976,0.0,1662758423,0,"Number of Letters/Flags:1-3,Personalization:ONE"
1,Cierra Joy (cjoy123),NaN,NaN,USD,07/04/2019,07/12/2019,0.0,NaN,NaN,Set of 3 Lanterns & Candles - Wedding - Engage...,...,NaN,Lodi,United States,Cierra Abdollahzadeh,CA,95240,0.0,1660352881,0,Personalization:Wedding -Sept 7th
2,Alason Moorhead (admoorhead),NaN,NaN,USD,07/02/2019,07/05/2019,0.0,NaN,NaN,"Cake Topper, Dr. Seuss, First Birthday, Second...",...,NaN,Amarillo,United States,Alason Moorhead,TX,79109,0.0,1655782068,0,"Number of Letters/Flags:1-3,Personalization:ON..."
3,lmcq741,NaN,NaN,USD,06/21/2019,07/05/2019,0.0,NaN,NaN,Set of 3 Lanterns & Candles - Wedding - Engage...,...,NaN,Norton,United States,Loren Day,MA,2766,0.0,1653796177,0,"Personalization:rehearsal dinner on August 9, ..."
4,Marissa Spacey (marissaspacey),NaN,NaN,USD,06/17/2019,06/20/2019,0.0,NaN,NaN,Wood Signs - Wedding Signs - Wood Wedding Signs,...,NaN,Bethpage,United States,Marissa Spacey,NY,11714,0.0,1651441691,0,"Stain Color:Dark,Size:8&quot; x 4&quot;,Person..."
5,S Shelburne (sshelburne12),NaN,NaN,USD,05/15/2019,05/28/2019,0.0,NaN,NaN,Set of 3 Lanterns & Candles - Wedding - Engage...,...,NaN,Midland,United States,Shannon Shelburne,VA,22728,0.0,1629862796,0,NaN
6,Amanda Nelson (zvq52mlo),NaN,NaN,USD,04/20/2019,04/28/2019,0.0,NaN,NaN,Wedding Centerpiece - Engagement Party Centerp...,...,NaN,CHICAGO,United States,Amanda Nelson,IL,60631,0.0,1618371745,0,NaN
7,Kadi Davis (dick0390),NaN,NaN,USD,07/09/2019,07/12/2019,0.0,NaN,NaN,"Cake Topper, Dr. Seuss, First Birthday, Second...",...,NaN,Stewartville,United States,Kadi Davis,MN,55976,0.0,1662758423,0,"Number of Letters/Flags:1-3,Personalization:ONE"
8,Cierra Joy (cjoy123),NaN,NaN,USD,07/04/2019,07/12/2019,0.0,NaN,NaN,Set of 3 Lanterns & Candles - Wedding - Engage...,...,NaN,Lodi,United States,Cierra Abdollahzadeh,CA,95240,0.0,1660352881,0,Personalization:Wedding -Sept 7th
9,Alason Moorhead (admoorhead),NaN,NaN,USD,07/02/2019,07/05/2019,0.0,NaN,NaN,"Cake Topper, Dr. Seuss, First Birthday, Second...",...,NaN,Amarillo,United States,Alason Moorhead,TX,79109,0.0,1655782068,0,"Number of Letters/Flags:1-3,Personalization:ON..."
10,lmcq741,NaN,NaN,USD,06/21/2019,07/05/2019,0.0,NaN,NaN,Set of 3 Lanterns & Candles - Wedding - Engage...,...,NaN,Norton,United States,Loren Day,MA,2766,0.0,1653796177,0,"Personalization:rehearsal dinner on August 9, ..."
11,Marissa Spacey (marissaspacey),NaN,NaN,USD,06/17/2019,06/20/2019,0.0,NaN,NaN,Wood Signs - Wedding Signs - Wood Wedding Signs,...,NaN,Bethpage,United States,Marissa Spacey,NY,11714,0.0,1651441691,0,"Stain Color:Dark,Size:8&quot; x 4&quot;,Person..."
12,S Shelburne (sshelburne12),NaN,NaN,USD,05/15/2019,05/28/2019,0.0,NaN,NaN,Set of 3 Lanterns & Candles - Wedding - Engage...,...,NaN,Midland,United States,Shannon Shelburne,VA,22728,0.0,1629862796,0,NaN
13,Amanda Nelson (zvq52mlo),NaN,NaN,USD,04/20/2019,04/28/2019,0.0,NaN,NaN,Wedding Centerpiece - Engagement Party Centerp...,...,NaN,CHICAGO,United States,Amanda Nelson,IL,60631,0.0,1618371745,0,NaN
14,Kadi Davis (dick0390),NaN,NaN,USD,07/09/2019,NaN,0.0,NaN,NaN,"Cake Topper, Dr. Seuss, First Birthday, Second...",...,NaN,Stewartville,United States,Kadi Davis,MN,55976,0.0,1662758423,0,"Number of Letters/Flags:1-3,Personalization:ONE"
15,Cierra Joy (cjoy123),NaN,NaN,USD,07/04/2019,NaN,0.0,NaN,NaN,Set of 3 Lanterns & Candles - Wedding - Engage...,...,NaN,Lodi,United States,Cierra Abdollahzadeh,CA,95240,0.0,1660352881,0,Personalization:Wedding -Sept 7th
16,Alason Moorhead (admoorhead),NaN,NaN,USD,07/02/2019,07/05/2019,0.0,NaN,NaN,"Cake Topper, Dr. Seuss, First Birthday, Second...",...,NaN,Amarillo,United States,Alason Moorhead,TX,79109,0.0,1655782068,0,"Number of Letters/Flags:1-3,Personalization:ON..."
17,lmcq741,NaN,NaN,USD,06/21/2019,07/05/2019,0.0,NaN,NaN,Set of 3 Lanterns & Candles - Wedding - Engage...,...,NaN,Norton,United States,Loren Day,MA,2766,0.0,1653796177,0,"Personalization:rehearsal dinner on August 9, ..."
18,Marissa Spacey (marissaspacey),NaN,NaN,USD,06/17/2019,06/20/2019,0.0,NaN,NaN,Wood Signs - Wedding Signs - Wood Wedding Signs,...,NaN,Bethpage,United States,Marissa Spacey,NY,11714,0.0,1651441691,0,"Stain Color:Dark,Size:8&quot; x 4&quot;,Person..."
19,S Shelburne (sshelburne12),NaN,NaN,USD,05/15/2019,05/28/2019,0.0,NaN,NaN,Set of 3 Lanterns & Candles - Wedding - Engage...,...,NaN,Midland,United States,Shannon Shelburne,VA,22728,0.0,1629862796,0,NaN
20,Amanda Nelson (zvq52mlo),NaN,NaN,USD,04/20/2019,04/28/2019,0.0,NaN,NaN,Wedding Centerpiece - Engagement Party Centerp...,...,NaN,CHICAGO,United States,Amanda Nelson,IL,60631,0.0,1618371745,0,NaN
21,Kadi Davis (dick0390),NaN,NaN,USD,07/09/2019,07/12/2019,0.0,NaN,NaN,"Cake Topper, Dr. Seuss, First Birthday, Second...",...,NaN,Stewartville,United States,Kadi Davis,MN,55976,0.0,1662758423,0,"Number of Letters/Flags:1-3,Personalization:ONE"
22,Cierra Joy (cjoy123),NaN,NaN,USD,07/04/2019,07/12/2019,0.0,NaN,NaN,Set of 3 Lanterns & Candles - Wedding - Engage...,...,NaN,Lodi,United States,Cierra Abdollahzadeh,CA,95240,0.0,1660352881,0,Personalization:Wedding -Sept 7th
23,Alason Moorhead (admoorhead),NaN,NaN,USD,07/02/2019,07/05/2019,0.0,NaN,NaN,"Cake Topper, Dr. Seuss, First Birthday, Second...",...,NaN,Amarillo,United States,Alason Moorhead,TX,79109,0.0,1655782068,0,"Number of Letters/Flags:1-3,Personalization:ON..."
24,lmcq741,NaN,NaN,USD,06/21/2019,07/05/2019,0.0,NaN,NaN,Set of 3 Lanterns & Candles - Wedding - Engage...,...,NaN,Norton,United States,Loren Day,MA,2766,0.0,1653796177,0,"Personalization:rehearsal dinner on August 9, ..."
25,Marissa Spacey (marissaspacey),NaN,NaN,USD,06/17/2019,06/20/2019,0.0,NaN,NaN,Wood Signs - Wedding Signs - Wood Wedding Signs,...,NaN,Bethpage,United States,Marissa Spacey,NY,11714,0.0,1651441691,0,"Stain Color:Dark,Size:8&quot; x 4&quot;,Person..."
26,S Shelburne (sshelburne12),NaN,NaN,USD,05/15/2019,05/28/2019,0.0,NaN,NaN,Set of 3 Lanterns & Candles - Wedding - Engage...,...,NaN,Midland,United States,Shannon Shelburne,VA,22728,0.0,1629862796,0,NaN
27,Amanda Nelson (zvq52mlo),NaN,NaN,USD,04/20/2019,04/28/2019,0.0,NaN,NaN,Wedding Centerpiece - Engagement Party Centerp...,...,NaN,CHICAGO,United States,Amanda Nelson,IL,60631,0.0,1618371745,0,NaN
28,Kadi Davis (dick0390),NaN,NaN,USD,07/09/2019,07/12/2019,0.0,NaN,NaN,"Cake Topper, Dr. Seuss, First Birthday, Second...",...,NaN,Stewartville,United States,Kadi Davis,MN,55976,0.0,1662758423,0,"Number of Letters/Flags:1-3,Personalization:ONE"
29,Cierra Joy (cjoy123),NaN,NaN,USD,07/04/2019,07/12/2019,0.0,NaN,NaN,Set of 3 Lanterns & Candles - Wedding - Engage...,...,NaN,Lodi,United States,Cierra Abdollahzadeh,CA,95240,0.0,1660352881,0,Personalization:Wedding -Sept 7th
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71,Kadi Davis (dick0390),NaN,NaN,USD,07/09/2019,07/12/2019,0.0,NaN,NaN,"Cake Topper, Dr. Seuss, First Birthday, Second...",...,NaN,Stewartville,United States,Kadi Davis,MN,55976,0.0,1662758423,0,"Number of Letters/Flags:1-3,Personalization:ONE"
72,Cierra Joy (cjoy123),NaN,NaN,USD,07/04/2019,07/12/2019,0.0,NaN,NaN,Set of 3 Lanterns & Candles - Wedding - Engage...,...,NaN,Lodi,United States,Cierra Abdollahzadeh,CA,95240,0.0,1660352881,0,Personalization:Wedding -Sept 7th
73,Alason Moorhead (admoorhead),NaN,NaN,USD,07/02/2019,07/05/2019,0.0,NaN,NaN,"Cake Topper, Dr. Seuss, First Birthday, Second...",...,NaN,Amarillo,United States,Alason Moorhead,TX,79109,0.0,1655782068,0,"Number of Letters/Flags:1-3,Personalization:ON..."
74,lmcq741,NaN,NaN,USD,06/21/2019,07/05/2019,0.0,NaN,NaN,Set of 3 Lanterns & Candles - Wedding - Engage...,...,NaN,Norton,United States,Loren Day,MA,2766,0.0,1653796177,0,"Personalization:rehearsal dinner on August 9, ..."
75,Marissa Spacey (marissaspacey),NaN,NaN,USD,06/17/2019,06/20/2019,0.0,NaN,NaN,Wood Signs - Wedding Signs - Wood Wedding Signs,...,NaN,Bethpage,United States,Marissa Spacey,NY,11714,0.0,1651441691,0,"Stain Color:Dark,Size:8&quot; x 4&quot;,Person..."
76,S Shelburne (sshelburne12),NaN,NaN,USD,05/15/2019,05/28/2019,0.0,NaN,NaN,Set of 3 Lanterns & Candles - Wedding - Engage...,...,NaN,Midland,United States,Shannon Shelburne,VA,22728,0.0,1629862796,0,NaN
77,Amanda Nelson (zvq52mlo),NaN,NaN,USD,04/20/2019,04/28/2019,0.0,NaN,NaN,Wedding Centerpiece - Engagement Party Centerp...,...,NaN,CHICAGO,United States,Amanda Nelson,IL,60631,0.0,1618371745,0,NaN
78,Jessica (jessicaholder4),NaN,NaN,USD,07/20/2019,07/21/2019,0.0,NaN,NaN,Test - Do Not Purchase,...,NaN,Dallas,United States,Jessica Holder,TX,75244,0.0,1668845593,0,NaN
79,Kadi Davis (dick0390),NaN,NaN,USD,07/09/2019,07/12/2019,0.0,NaN,NaN,"Cake Topper, Dr. Seuss, First Birthday, Second...",...,NaN,Stewartville,United States,Kadi Davis,MN,55976,0.0,1662758423,0,"Number of Letters/Flags:1-3,Personalization:ONE"
80,Cierra Joy (cjoy123),NaN,NaN,USD,07/04/2019,07/12/2019,0.0,NaN,NaN,Set of 3 Lanterns & Candles - Wedding - Engage...,...,NaN,Lodi,United States,Cierra Abdollahzadeh,CA,95240,0.0,1660352881,0,Personalization:Wedding -Sept 7th
81,Alason Moorhead (admoorhead),NaN,NaN,USD,07/02/2019,07/05/2019,0.0,NaN,NaN,"Cake Topper, Dr. Seuss, First Birthday, Second...",...,NaN,Amarillo,United States,Alason Moorhead,TX,79109,0.0,1655782068,0,"Number of Letters/Flags:1-3,Personalization:ON..."
82,lmcq741,NaN,NaN,USD,06/21/2019,07/05/2019,0.0,NaN,NaN,Set of 3 Lanterns & Candles - Wedding - Engage...,...,NaN,Norton,United States,Loren Day,MA,2766,0.0,1653796177,0,"Personalization:rehearsal dinner on August 9, ..."
83,Marissa Spacey (marissaspacey),NaN,NaN,USD,06/17/2019,06/20/2019,0.0,NaN,NaN,Wood Signs - Wedding Signs - Wood Wedding Signs,...,NaN,Bethpage,United States,Marissa Spacey,NY,11714,0.0,1651441691,0,"Stain Color:Dark,Size:8&quot; x 4&quot;,Person..."
84,S Shelburne (sshelburne12),NaN,NaN,USD,05/15/2019,05/28/2019,0.0,NaN,NaN,Set of 3 Lanterns & Candles - Wedding - Engage...,...,NaN,Midland,United States,Shannon Shelburne,VA,22728,0.0,1629862796,0,NaN
85,Amanda Nelson (zvq52mlo),NaN,NaN,USD,04/20/2019,04/28/2019,0.0,NaN,NaN,Wedding Centerpiece - Engagement Party Centerp...,...,NaN,CHICAGO,United States,Amanda Nelson,IL,60631,0.0,1618371745,0,NaN
86,Jessica (jessicaholder4),NaN,NaN,USD,07/20/2019,NaN,0.0,NaN,NaN,Test - Do Not Purchase,...,NaN,Dallas,United States,Jessica Holder,TX,75244,0.0,1668845593,0,NaN
87,Kadi Davis (dick0390),NaN,NaN,USD,07/09/2019,07/12/2019,0.0,NaN,NaN,"Cake Topper, Dr. Seuss, First Birthday, Second...",...,NaN,Stewartville,United States,Kadi Davis,MN,55976,0.0,1662758423,0,"Number of Letters/Flags:1-3,Personalization:ONE"
88,Cierra Joy (cjoy123),NaN,NaN,USD,07/04/2019,07/12/2019,0.0,NaN,NaN,Set of 3 Lanterns & Candles - Wedding - Engage...,...,NaN,Lodi,United States,Cierra Abdollahzadeh,CA,95240,0.0,1660352881,0,Personalization:Wedding -Sept 7th
89,Alason Moorhead (admoorhead),NaN,NaN,USD,07/02/2019,07/05/2019,0.0,NaN,NaN,"Cake Topper, Dr. Seuss, First Birthday, Second...",...,NaN,Amarillo,United States,Alason Moorhead,TX,79109,0.0,1655782068,0,"Number of Letters/Flags:1-3,Personalization:ON..."
90,lmcq741,NaN,NaN,USD,06/21/2019,07/05/2019,0.0,NaN,NaN,Set of 3 Lanterns & Candles - Wedding - Engage...,...,NaN,Norton,United States,Loren Day,MA,2766,0.0,1653796177,0,"Personalization:rehearsal dinner on August 9, ..."
91,Marissa Spacey (marissaspacey),NaN,NaN,USD,06/17/2019,06/20/2019,0.0,NaN,NaN,Wood Signs - Wedding Signs - Wood Wedding Signs,...,NaN,Bethpage,United States,Marissa Spacey,NY,11714,0.0,1651441691,0,"Stain Color:Dark,Size:8&quot; x 4&quot;,Person..."
92,S Shelburne (sshelburne12),NaN,NaN,USD,05/15/2019,05/28/2019,0.0,NaN,NaN,Set of 3 Lanterns & Candles - Wedding - Engage...,...,NaN,Midland,United States,Shannon Shelburne,VA,22728,0.0,1629862796,0,NaN
93,Amanda Nelson (zvq52mlo),NaN,NaN,USD,04/20/2019,04/28/2019,0.0,NaN,NaN,Wedding Centerpiece - Engagement Party Centerp...,...,NaN,CHICAGO,United States,Amanda Nelson,IL,60631,0.0,1618371745,0,NaN
94,Kadi Davis (dick0390),NaN,NaN,USD,07/09/2019,07/12/2019,0.0,NaN,NaN,"Cake Topper, Dr. Seuss, First Birthday, Second...",...,NaN,Stewartville,United States,Kadi Davis,MN,55976,0.0,1662758423,0,"Number of Letters/Flags:1-3,Personalization:ONE"
95,Cierra Joy (cjoy123),NaN,NaN,USD,07/04/2019,07/12/2019,0.0,NaN,NaN,Set of 3 Lanterns & Candles - Wedding - Engage...,...,NaN,Lodi,United States,Cierra Abdollahzadeh,CA,95240,0.0,1660352881,0,Personalization:Wedding -Sept 7th
96,Alason Moorhead (admoorhead),NaN,NaN,USD,07/02/2019,07/05/2019,0.0,NaN,NaN,"Cake Topper, Dr. Seuss, First Birthday, Second...",...,NaN,Amarillo,United States,Alason Moorhead,TX,79109,0.0,1655782068,0,"Number of Letters/Flags:1-3,Personalization:ON..."
97,lmcq741,NaN,NaN,USD,06/21/2019,07/05/2019,0.0,NaN,NaN,Set of 3 Lanterns & Candles - Wedding - Engage...,...,NaN,Norton,United States,Loren Day,MA,2766,0.0,1653796177,0,"Personalization:rehearsal dinner on August 9, ..."
98,Marissa Spacey (marissaspacey),NaN,NaN,USD,06/17/2019,06/20/2019,0.0,NaN,NaN,Wood Signs - Wedding Signs - Wood Wedding Signs,...,NaN,Bethpage,United States,Marissa Spacey,NY,11714,0.0,1651441691,0,"Stain Color:Dark,Size:8&quot; x 4&quot;,Person..."
99,S Shelburne (sshelburne12),NaN,NaN,USD,05/15/2019,05/28/2019,0.0,NaN,NaN,Set of 3 Lanterns & Candles - Wedding - Engage...,...,NaN,Midland,United States,Shannon Shelburne,VA,22728,0.0,1629862796,0,NaN
100,Amanda Nelson (zvq52mlo),NaN,NaN,USD,04/20/2019,04/28/2019,0.0,NaN,NaN,Wedding Centerpiece - Engagement Party Centerp...,...,NaN,CHICAGO,United States,Amanda Nelson,IL,60631,0.0,1618371745,0,NaN

In [127]:
df.to_csv(f"/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/Data/EtsySoldOrderItems_cumm.csv",index=False,header=True,encoding="UTF-8")

# Direct Checkout

In [128]:
path = r'/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/ShopDataCSV' # use your path
all_files = glob.glob(path + "/EtsyDirectCheckout*.csv")

li = []

for filename in all_files:
    df = pd.read_csv(filename, index_col=None, header=0)
    li.append(df)
    print(filename)
    
df = pd.concat(li, axis=0, ignore_index=True, sort=True)

df

/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/ShopDataCSV/EtsyDirectCheckoutPayments071919.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/ShopDataCSV/EtsyDirectCheckoutPayments072219.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/ShopDataCSV/EtsyDirectCheckoutPayments072019.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/ShopDataCSV/EtsyDirectCheckoutPayments071819.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/ShopDataCSV/EtsyDirectCheckoutPayments072119.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/ShopDataCSV/EtsyDirectCheckoutPayments071219.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/ShopDataCSV/EtsyDirectCheckoutPayments070919.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/ShopDataCSV/EtsyDirectCheckoutPayments071019.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/ShopDataCSV/EtsyDirectCheckoutPayments071419.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/ShopDataCSV/EtsyDirectCheckoutPayments071619.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/ShopDataCSV/EtsyDirectCheckoutPayments071119.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/ShopDataCSV/EtsyDirectCheckoutPayments071319.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/ShopDataCSV/EtsyDirectCheckoutPayments071719.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/ShopDataCSV/EtsyDirectCheckoutPayments071519.csv

,Adjusted Fees,Adjusted Gross,Adjusted Net,Buyer,Buyer Name,Buyer Username,Currency,Exchange Rate,Fees,Funds Available,...,Order ID,Order Type,Payment ID,Payment Type,Posted Fees,Posted Gross,Posted Net,Refund Amount,Status,VAT Amount
0,NaN,NaN,NaN,Amanda Nelson,Amanda Nelson,zvq52mlo,USD,1,3.52,04/22/2019,...,1441612324,online,53895683736,online_cc,3.52,108.97,105.45,0,SETTLED,0.0
1,NaN,NaN,NaN,Shannon Shelburne,S Shelburne,sshelburne12,USD,1,4.04,05/18/2019,...,1461258703,online,54403029298,online_cc,4.04,126.36,122.32,0,SETTLED,0.0
2,NaN,NaN,NaN,Marissa Spacey,Marissa Spacey,marissaspacey,USD,1,0.65,06/20/2019,...,1465581068,online,55035728452,online_cc,0.65,12.36,11.71,0,SETTLED,0.0
3,NaN,NaN,NaN,Loren Day,NaN,lmcq741,USD,1,5.22,06/24/2019,...,1467289834,online,57101879075,online_cc,5.22,165.56,160.34,0,SETTLED,0.0
4,NaN,NaN,NaN,Alason Moorhead,Alason Moorhead,admoorhead,USD,1,0.77,07/05/2019,...,1471406642,online,55326160410,online_cc,0.77,17.46,16.69,0,SETTLED,0.0
5,NaN,NaN,NaN,Cierra Abdollahzadeh,Cierra Joy,cjoy123,USD,1,5.20,07/07/2019,...,1471997258,online,57336925567,online_cc,5.20,164.96,159.76,0,SETTLED,0.0
6,NaN,NaN,NaN,Kadi Davis,Kadi Davis,dick0390,USD,1,0.75,07/12/2019,...,1482734683,online,55433131960,online_cc,0.75,15.53,14.78,0,SETTLED,0.0
7,NaN,NaN,NaN,Amanda Nelson,Amanda Nelson,zvq52mlo,USD,1,3.52,04/22/2019,...,1441612324,online,53895683736,online_cc,3.52,108.97,105.45,0,SETTLED,0.0
8,NaN,NaN,NaN,Shannon Shelburne,S Shelburne,sshelburne12,USD,1,4.04,05/18/2019,...,1461258703,online,54403029298,online_cc,4.04,126.36,122.32,0,SETTLED,0.0
9,NaN,NaN,NaN,Marissa Spacey,Marissa Spacey,marissaspacey,USD,1,0.65,06/20/2019,...,1465581068,online,55035728452,online_cc,0.65,12.36,11.71,0,SETTLED,0.0
10,NaN,NaN,NaN,Loren Day,NaN,lmcq741,USD,1,5.22,06/24/2019,...,1467289834,online,57101879075,online_cc,5.22,165.56,160.34,0,SETTLED,0.0
11,NaN,NaN,NaN,Alason Moorhead,Alason Moorhead,admoorhead,USD,1,0.77,07/05/2019,...,1471406642,online,55326160410,online_cc,0.77,17.46,16.69,0,SETTLED,0.0
12,NaN,NaN,NaN,Cierra Abdollahzadeh,Cierra Joy,cjoy123,USD,1,5.20,07/07/2019,...,1471997258,online,57336925567,online_cc,5.20,164.96,159.76,0,SETTLED,0.0
13,NaN,NaN,NaN,Kadi Davis,Kadi Davis,dick0390,USD,1,0.75,07/12/2019,...,1482734683,online,55433131960,online_cc,0.75,15.53,14.78,0,SETTLED,0.0
14,NaN,NaN,NaN,Jessica Holder,Jessica,jessicaholder4,USD,1,0.28,07/21/2019,...,1487089393,online,57615027691,online_cc,0.28,1.00,0.72,0,SETTLED,0.0
15,NaN,NaN,NaN,Amanda Nelson,Amanda Nelson,zvq52mlo,USD,1,3.52,04/22/2019,...,1441612324,online,53895683736,online_cc,3.52,108.97,105.45,0,SETTLED,0.0
16,NaN,NaN,NaN,Shannon Shelburne,S Shelburne,sshelburne12,USD,1,4.04,05/18/2019,...,1461258703,online,54403029298,online_cc,4.04,126.36,122.32,0,SETTLED,0.0
17,NaN,NaN,NaN,Marissa Spacey,Marissa Spacey,marissaspacey,USD,1,0.65,06/20/2019,...,1465581068,online,55035728452,online_cc,0.65,12.36,11.71,0,SETTLED,0.0
18,NaN,NaN,NaN,Loren Day,NaN,lmcq741,USD,1,5.22,06/24/2019,...,1467289834,online,57101879075,online_cc,5.22,165.56,160.34,0,SETTLED,0.0
19,NaN,NaN,NaN,Alason Moorhead,Alason Moorhead,admoorhead,USD,1,0.77,07/05/2019,...,1471406642,online,55326160410,online_cc,0.77,17.46,16.69,0,SETTLED,0.0
20,NaN,NaN,NaN,Cierra Abdollahzadeh,Cierra Joy,cjoy123,USD,1,5.20,07/07/2019,...,1471997258,online,57336925567,online_cc,5.20,164.96,159.76,0,SETTLED,0.0
21,NaN,NaN,NaN,Kadi Davis,Kadi Davis,dick0390,USD,1,0.75,07/12/2019,...,1482734683,online,55433131960,online_cc,0.75,15.53,14.78,0,SETTLED,0.0
22,NaN,NaN,NaN,Jessica Holder,Jessica,jessicaholder4,USD,1,0.28,07/21/2019,...,1487089393,online,57615027691,online_cc,0.28,1.00,0.72,0,SETTLED,0.0
23,NaN,NaN,NaN,Amanda Nelson,Amanda Nelson,zvq52mlo,USD,1,3.52,04/22/2019,...,1441612324,online,53895683736,online_cc,3.52,108.97,105.45,0,SETTLED,0.0
24,NaN,NaN,NaN,Shannon Shelburne,S Shelburne,sshelburne12,USD,1,4.04,05/18/2019,...,1461258703,online,54403029298,online_cc,4.04,126.36,122.32,0,SETTLED,0.0
25,NaN,NaN,NaN,Marissa Spacey,Marissa Spacey,marissaspacey,USD,1,0.65,06/20/2019,...,1465581068,online,55035728452,online_cc,0.65,12.36,11.71,0,SETTLED,0.0
26,NaN,NaN,NaN,Loren Day,NaN,lmcq741,USD,1,5.22,06/24/2019,...,1467289834,online,57101879075,online_cc,5.22,165.56,160.34,0,SETTLED,0.0
27,NaN,NaN,NaN,Alason Moorhead,Alason Moorhead,admoorhead,USD,1,0.77,07/05/2019,...,1471406642,online,55326160410,online_cc,0.77,17.46,16.69,0,SETTLED,0.0
28,NaN,NaN,NaN,Cierra Abdollahzadeh,Cierra Joy,cjoy123,USD,1,5.20,07/07/2019,...,1471997258,online,57336925567,online_cc,5.20,164.96,159.76,0,SETTLED,0.0
29,NaN,NaN,NaN,Kadi Davis,Kadi Davis,dick0390,USD,1,0.75,07/12/2019,...,1482734683,online,55433131960,online_cc,0.75,15.53,14.78,0,SETTLED,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71,NaN,NaN,NaN,Cierra Abdollahzadeh,Cierra Joy,cjoy123,USD,1,5.20,07/07/2019,...,1471997258,online,57336925567,online_cc,5.20,164.96,159.76,0,SETTLED,0.0
72,NaN,NaN,NaN,Kadi Davis,Kadi Davis,dick0390,USD,1,0.75,07/12/2019,...,1482734683,online,55433131960,online_cc,0.75,15.53,14.78,0,SETTLED,0.0
73,NaN,NaN,NaN,Amanda Nelson,Amanda Nelson,zvq52mlo,USD,1,3.52,04/22/2019,...,1441612324,online,53895683736,online_cc,3.52,108.97,105.45,0,SETTLED,0.0
74,NaN,NaN,NaN,Shannon Shelburne,S Shelburne,sshelburne12,USD,1,4.04,05/18/2019,...,1461258703,online,54403029298,online_cc,4.04,126.36,122.32,0,SETTLED,0.0
75,NaN,NaN,NaN,Marissa Spacey,Marissa Spacey,marissaspacey,USD,1,0.65,06/20/2019,...,1465581068,online,55035728452,online_cc,0.65,12.36,11.71,0,SETTLED,0.0
76,NaN,NaN,NaN,Loren Day,NaN,lmcq741,USD,1,5.22,06/24/2019,...,1467289834,online,57101879075,online_cc,5.22,165.56,160.34,0,SETTLED,0.0
77,NaN,NaN,NaN,Alason Moorhead,Alason Moorhead,admoorhead,USD,1,0.77,07/05/2019,...,1471406642,online,55326160410,online_cc,0.77,17.46,16.69,0,SETTLED,0.0
78,NaN,NaN,NaN,Cierra Abdollahzadeh,Cierra Joy,cjoy123,USD,1,5.20,07/07/2019,...,1471997258,online,57336925567,online_cc,5.20,164.96,159.76,0,SETTLED,0.0
79,NaN,NaN,NaN,Kadi Davis,Kadi Davis,dick0390,USD,1,0.75,07/12/2019,...,1482734683,online,55433131960,online_cc,0.75,15.53,14.78,0,SETTLED,0.0
80,NaN,NaN,NaN,Amanda Nelson,Amanda Nelson,zvq52mlo,USD,1,3.52,04/22/2019,...,1441612324,online,53895683736,online_cc,3.52,108.97,105.45,0,SETTLED,0.0
81,NaN,NaN,NaN,Shannon Shelburne,S Shelburne,sshelburne12,USD,1,4.04,05/18/2019,...,1461258703,online,54403029298,online_cc,4.04,126.36,122.32,0,SETTLED,0.0
82,NaN,NaN,NaN,Marissa Spacey,Marissa Spacey,marissaspacey,USD,1,0.65,06/20/2019,...,1465581068,online,55035728452,online_cc,0.65,12.36,11.71,0,SETTLED,0.0
83,NaN,NaN,NaN,Loren Day,NaN,lmcq741,USD,1,5.22,06/24/2019,...,1467289834,online,57101879075,online_cc,5.22,165.56,160.34,0,SETTLED,0.0
84,NaN,NaN,NaN,Alason Moorhead,Alason Moorhead,admoorhead,USD,1,0.77,07/05/2019,...,1471406642,online,55326160410,online_cc,0.77,17.46,16.69,0,SETTLED,0.0
85,NaN,NaN,NaN,Cierra Abdollahzadeh,Cierra Joy,cjoy123,USD,1,5.20,07/07/2019,...,1471997258,online,57336925567,online_cc,5.20,164.96,159.76,0,SETTLED,0.0
86,NaN,NaN,NaN,Kadi Davis,Kadi Davis,dick0390,USD,1,0.75,07/12/2019,...,1482734683,online,55433131960,online_cc,0.75,15.53,14.78,0,SETTLED,0.0
87,NaN,NaN,NaN,Amanda Nelson,Amanda Nelson,zvq52mlo,USD,1,3.52,04/22/2019,...,1441612324,online,53895683736,online_cc,3.52,108.97,105.45,0,SETTLED,0.0
88,NaN,NaN,NaN,Shannon Shelburne,S Shelburne,sshelburne12,USD,1,4.04,05/18/2019,...,1461258703,online,54403029298,online_cc,4.04,126.36,122.32,0,SETTLED,0.0
89,NaN,NaN,NaN,Marissa Spacey,Marissa Spacey,marissaspacey,USD,1,0.65,06/20/2019,...,1465581068,online,55035728452,online_cc,0.65,12.36,11.71,0,SETTLED,0.0
90,NaN,NaN,NaN,Loren Day,NaN,lmcq741,USD,1,5.22,06/24/2019,...,1467289834,online,57101879075,online_cc,5.22,165.56,160.34,0,SETTLED,0.0
91,NaN,NaN,NaN,Alason Moorhead,Alason Moorhead,admoorhead,USD,1,0.77,07/05/2019,...,1471406642,online,55326160410,online_cc,0.77,17.46,16.69,0,SETTLED,0.0
92,NaN,NaN,NaN,Cierra Abdollahzadeh,Cierra Joy,cjoy123,USD,1,5.20,07/07/2019,...,1471997258,online,57336925567,online_cc,5.20,164.96,159.76,0,SETTLED,0.0
93,NaN,NaN,NaN,Kadi Davis,Kadi Davis,dick0390,USD,1,0.75,07/12/2019,...,1482734683,online,55433131960,online_cc,0.75,15.53,14.78,0,SETTLED,0.0
94,NaN,NaN,NaN,Amanda Nelson,Amanda Nelson,zvq52mlo,USD,1,3.52,04/22/2019,...,1441612324,online,53895683736,online_cc,3.52,108.97,105.45,0,SETTLED,0.0
95,NaN,NaN,NaN,Shannon Shelburne,S Shelburne,sshelburne12,USD,1,4.04,05/18/2019,...,1461258703,online,54403029298,online_cc,4.04,126.36,122.32,0,SETTLED,0.0
96,NaN,NaN,NaN,Marissa Spacey,Marissa Spacey,marissaspacey,USD,1,0.65,06/20/2019,...,1465581068,online,55035728452,online_cc,0.65,12.36,11.71,0,SETTLED,0.0
97,NaN,NaN,NaN,Loren Day,NaN,lmcq741,USD,1,5.22,06/24/2019,...,1467289834,online,57101879075,online_cc,5.22,165.56,160.34,0,SETTLED,0.0
98,NaN,NaN,NaN,Alason Moorhead,Alason Moorhead,admoorhead,USD,1,0.77,07/05/2019,...,1471406642,online,55326160410,online_cc,0.77,17.46,16.69,0,SETTLED,0.0
99,NaN,NaN,NaN,Cierra Abdollahzadeh,Cierra Joy,cjoy123,USD,1,5.20,07/07/2019,...,1471997258,online,57336925567,online_cc,5.20,164.96,159.76,0,SETTLED,0.0
100,NaN,NaN,NaN,Kadi Davis,Kadi Davis,dick0390,USD,1,0.75,07/12/2019,...,1482734683,online,55433131960,online_cc,0.75,15.53,14.78,0,SETTLED,0.0

In [129]:
df.to_csv(f"/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/Data/EtsyDirectCheckout_cumm.csv",index=False,header=True,encoding="UTF-8")

# Deposits

In [130]:
path = r'/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/ShopDataCSV' # use your path
all_files = glob.glob(path + "/EtsyDeposits*.csv")

li = []

for filename in all_files:
    df = pd.read_csv(filename, index_col=None, header=0)
    li.append(df)
    print(filename)
    
df = pd.concat(li, axis=0, ignore_index=True, sort=True)

df

/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/ShopDataCSV/EtsyDeposits071619.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/ShopDataCSV/EtsyDeposits071419.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/ShopDataCSV/EtsyDeposits070919.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/ShopDataCSV/EtsyDeposits071019.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/ShopDataCSV/EtsyDeposits071219.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/ShopDataCSV/EtsyDeposits071519.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/ShopDataCSV/EtsyDeposits071719.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/ShopDataCSV/EtsyDeposits071319.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/ShopDataCSV/EtsyDeposits071119.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/ShopDataCSV/EtsyDeposits072019.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/ShopDataCSV/EtsyDeposits072219.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/ShopDataCSV/EtsyDeposits071919.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/ShopDataCSV/EtsyDeposits072119.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/ShopDataCSV/EtsyDeposits071819.csv

    Amount  Bank Account Ending Digits Currency            Date    Status
0    74.70                        6149      USD  April 22, 2019  Executed
1   100.57                        6149      USD    May 20, 2019  Executed
2   160.95                        6149      USD   June 24, 2019  Executed
3   166.79                        6149      USD    July 8, 2019  Executed
4    13.80                        6149      USD   July 15, 2019  Executed
5    74.70                        6149      USD  April 22, 2019  Executed
6   100.57                        6149      USD    May 20, 2019  Executed
7   160.95                        6149      USD   June 24, 2019  Executed
8   166.79                        6149      USD    July 8, 2019  Executed
9    74.70                        6149      USD  April 22, 2019  Executed
10  100.57                        6149      USD    May 20, 2019  Executed
11  160.95                        6149      USD   June 24, 2019  Executed
12  166.79                        6149      USD    July 8, 2019  Executed
13   74.70                        6149      USD  April 22, 2019  Executed
14  100.57                        6149      USD    May 20, 2019  Executed
15  160.95                        6149      USD   June 24, 2019  Executed
16  166.79                        6149      USD    July 8, 2019  Executed
17   74.70                        6149      USD  April 22, 2019  Executed
18  100.57                        6149      USD    May 20, 2019  Executed
19  160.95                        6149      USD   June 24, 2019  Executed
20  166.79                        6149      USD    July 8, 2019  Executed
21   74.70                        6149      USD  April 22, 2019  Executed
22  100.57                        6149      USD    May 20, 2019  Executed
23  160.95                        6149      USD   June 24, 2019  Executed
24  166.79                        6149      USD    July 8, 2019  Executed
25   13.80                        6149      USD   July 15, 2019  Executed
26   74.70                        6149      USD  April 22, 2019  Executed
27  100.57                        6149      USD    May 20, 2019  Executed
28  160.95                        6149      USD   June 24, 2019  Executed
29  166.79                        6149      USD    July 8, 2019  Executed
..     ...                         ...      ...             ...       ...
34  166.79                        6149      USD    July 8, 2019  Executed
35   74.70                        6149      USD  April 22, 2019  Executed
36  100.57                        6149      USD    May 20, 2019  Executed
37  160.95                        6149      USD   June 24, 2019  Executed
38  166.79                        6149      USD    July 8, 2019  Executed
39   74.70                        6149      USD  April 22, 2019  Executed
40  100.57                        6149      USD    May 20, 2019  Executed
41  160.95                        6149      USD   June 24, 2019  Executed
42  166.79                        6149      USD    July 8, 2019  Executed
43   13.80                        6149      USD   July 15, 2019  Executed
44   74.70                        6149      USD  April 22, 2019  Executed
45  100.57                        6149      USD    May 20, 2019  Executed
46  160.95                        6149      USD   June 24, 2019  Executed
47  166.79                        6149      USD    July 8, 2019  Executed
48   13.80                        6149      USD   July 15, 2019  Executed
49   74.70                        6149      USD  April 22, 2019  Executed
50  100.57                        6149      USD    May 20, 2019  Executed
51  160.95                        6149      USD   June 24, 2019  Executed
52  166.79                        6149      USD    July 8, 2019  Executed
53   13.80                        6149      USD   July 15, 2019  Executed
54   74.70                        6149      USD  April 22, 2019  Executed
55  100.57                        6149      USD    May 20, 2019  Executed
56  160.95                        6149      USD   June 24, 2019  Executed
57  166.79                        6149      USD    July 8, 2019  Executed
58   13.80                        6149      USD   July 15, 2019  Executed
59   74.70                        6149      USD  April 22, 2019  Executed
60  100.57                        6149      USD    May 20, 2019  Executed
61  160.95                        6149      USD   June 24, 2019  Executed
62  166.79                        6149      USD    July 8, 2019  Executed
63   13.80                        6149      USD   July 15, 2019  Executed

[64 rows x 5 columns]

In [131]:
df.to_csv(f"/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/Data/EtsyDeposits_cumm.csv",index=False,header=True,encoding="UTF-8")

# Competitor Sales

In [161]:
df = pd.read_csv('/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/eRank_CompetitorSales_071519.csv', index_col=None, header=0)
df2 = pd.read_csv('/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/eRank_CompetitorSales_072219.csv', index_col=None, header=0)

li=[df,df2]

In [162]:
from datetime import datetime, date, time, timedelta

li2=[]
li3=[]

today=date.today()
yesterday = date.today() - timedelta(days=1)
yesterday_year=yesterday.strftime('%Y')

for item in li:
    comp_sales_daily = item.drop(item.iloc[:,11:14],axis=1)
    comp_sales_daily.drop(comp_sales_daily.columns[[0,2,3,-1]],axis=1,inplace=True)
    # Get df column values
    comp_sales_daily_columns = comp_sales_daily.columns.get_values()

    # Turn column values to list
    comp_sales_daily_columns=comp_sales_daily_columns.tolist()
    
    id_vars=['Shop']

    # Identify values for melt
    for item in id_vars:
        comp_sales_daily_columns.remove(item)

    # Melt df 
    comp_sales_daily2=pd.melt(comp_sales_daily, id_vars=id_vars, value_vars=comp_sales_daily_columns)

    # Add year and change str to datetime
    comp_sales_daily2['date'] = yesterday_year + comp_sales_daily2['variable'].astype(str)
    comp_sales_daily2['date']= pd.to_datetime(comp_sales_daily2['date'], format="%Y%a%d-%b")

    # Drop column no longer needed 
    comp_sales_daily2=comp_sales_daily2.drop(['variable'],axis=1)
    
    # Rename value column to sales
    comp_sales_daily2=comp_sales_daily2.rename(columns={'value':'sales'})

    comp_sales_daily2['week'] = (comp_sales_daily2['date'] + pd.DateOffset(days=1)).dt.week
    comp_sales_daily2
    cur_week_no=comp_sales_daily2.iloc[0]['week']
    
    li2.append(comp_sales_daily2)
for item in li:
   
    comp_sales_sum=item.drop(item.iloc[:,4:12],axis=1)
    comp_sales_sum.drop(comp_sales_sum.columns[[0,2]],axis=1,inplace=True)
    
    # Rename original week column
    comp_sales_sum=comp_sales_sum.rename(columns={'Week':'weeklySales'})
    
    comp_sales_sum['week']=cur_week_no
    li3.append(comp_sales_sum)

In [163]:
comp_sales_daily_df = pd.concat(li2, axis=0, ignore_index=True, sort=False)
comp_sales_sum_df = pd.concat(li3, axis=0, ignore_index=True, sort=False)

comp_sales_daily_df.head()

                Shop sales       date  week
0            Rawkrft   194 2019-07-09    28
1       caketothetop    20 2019-07-09    28
2  MoonlightWeddings    11 2019-07-09    28
3       GFTWoodcraft     1 2019-07-09    28
4         Fancyitup1     1 2019-07-09    28

In [164]:
comp_sales_sum_df.head()

,Shop,Notes,weeklySales,Total Sales,Active Listings,week
0,Rawkrft,Cake Toppers,"1,151","7,189",24,29
1,caketothetop,Click to add note,114,"18,684",301,29
2,MoonlightWeddings,Click to add note,50,"3,652",371,29
3,GFTWoodcraft,Click to add note,21,"8,001",105,29
4,Fancyitup1,Click to add note,7,"1,308",384,29

In [165]:
comp_sales_daily_df.to_csv(f"/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/Data/eRank_CompetitorSalesDaily_cumm.csv",index=False,header=True,encoding="UTF-8")
comp_sales_sum_df.to_csv(f"/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/Data/eRank_CompetitorSalesSummary_cumm.csv",index=False,header=True,encoding="UTF-8")

# Competitor Listings

In [200]:
import os
from time import sleep
competitors=['caketothetop','Rawkrft',
 'MoonlightWeddings',
 'HomegrownChicDesigns',
 'GFTWoodcraft',
 'RusticWithElegance',
 'Fancyitup1',
 'Designingweddings']

for competitor in competitors:
    path = r'/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData' # use your path
    all_files = glob.glob(f"{path}/eRank_CompetitorListings_{competitor}*.csv")

    li = []

    for filename in all_files:
        df = pd.read_csv(filename, index_col=None, header=0)
        first_split=filename.split('_', 3)[-1]
        date=first_split.split('.',1)[0]
        df['date']= date
        li.append(df)


    
    df = pd.concat(li, axis=0, ignore_index=True, sort=True)
    
    df['Shop']=competitor
    df.drop(df.columns[[0]],axis=1,inplace=True)
    
    df_csv_fp=f"/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/Data/eRank_CompetitorListings.csv"

     # Create or append to csv
    if not os.path.isfile(df_csv_fp):
        df.to_csv(df_csv_fp, header='column_names')
    else: # else it exists so append without writing the header
        df.to_csv(df_csv_fp, mode='a', header=False)

# Competitor Tags

In [203]:
import os
from time import sleep
competitors=['caketothetop','Rawkrft',
 'MoonlightWeddings',
 'HomegrownChicDesigns',
 'GFTWoodcraft',
 'RusticWithElegance',
 'Fancyitup1',
 'Designingweddings']

for competitor in competitors:
    path = r'/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData' # use your path
    all_files = glob.glob(f"{path}/eRank_CompetitorTags_{competitor}*.csv")

    li = []

    for filename in all_files:
        df = pd.read_csv(filename, index_col=None, header=0)
        first_split=filename.split('_', 3)[-1]
        date=first_split.split('.',1)[0]
        df['date']= date
        li.append(df)


    
    df = pd.concat(li, axis=0, ignore_index=True, sort=True)
    
    df['Shop']=competitor
    
    df_csv_fp=f"/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/Data/eRank_CompetitorTags.csv"

     # Create or append to csv
    if not os.path.isfile(df_csv_fp):
        df.to_csv(df_csv_fp, header='column_names')
    else: # else it exists so append without writing the header
        df.to_csv(df_csv_fp, mode='a', header=False)

# Grades (SEO)

In [214]:
path = r'/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData' # use your path
all_files = glob.glob(path + "/eRank_SEORankings*.csv")

li = []

for filename in all_files:
    df = pd.read_csv(filename, index_col=None, header=0)
    first_split=filename.split('_', 3)[-1]
    date=first_split.split('.',1)[0]
    df['record_date']= date
    li.append(df)
    print(filename)
    
df = pd.concat(li, axis=0, ignore_index=True, sort=True)

df.head()

/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/eRank_SEORankings_071719.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/eRank_SEORankings_071519.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/eRank_SEORankings_071419.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/eRank_SEORankings_071619.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/eRank_SEORankings_072119.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/eRank_SEORankings_071819.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/eRank_SEORankings_072219.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/eRank_SEORankings_072019.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/eRank_SEORankings_071919.csv

,#,ConversionRate,ConversionRate ItemsSold,ListingID,ListingTitle,MainImage,SEOGrade,SEOSuggestions,SKU,VisibilityScore,record_date
0,1,0.0%,0,680064082,"Picture Centerpiece for Weddings, Anniversary ...",NaN,A,4,NaN,95%,071719
1,13,0.0%,0,688465922,Geometric Light Centerpiece : Marie \t\t\t\t\t...,NaN,A,3,NaN,55%,071719
2,16,0.0%,0,693930997,Orb Wedding Centerpiece : Gloria GM \t\t\t\t\t...,NaN,A,3,NaN,88%,071719
3,19,0.0%,0,700377146,Wood Lantern Centerpiece : Catalina PM - LANTE...,NaN,A,5,NaN,29%,071719
4,20,0.0%,0,700382982,Orb Wedding Centerpiece : Gloria GM-ORB ONLY \...,NaN,A,3,NaN,44%,071719

In [215]:
df.drop(columns=['MainImage'],axis=1,inplace=True)

In [216]:
df.head()

,#,ConversionRate,ConversionRate ItemsSold,ListingID,ListingTitle,SEOGrade,SEOSuggestions,SKU,VisibilityScore,record_date
0,1,0.0%,0,680064082,"Picture Centerpiece for Weddings, Anniversary ...",A,4,NaN,95%,071719
1,13,0.0%,0,688465922,Geometric Light Centerpiece : Marie \t\t\t\t\t...,A,3,NaN,55%,071719
2,16,0.0%,0,693930997,Orb Wedding Centerpiece : Gloria GM \t\t\t\t\t...,A,3,NaN,88%,071719
3,19,0.0%,0,700377146,Wood Lantern Centerpiece : Catalina PM - LANTE...,A,5,NaN,29%,071719
4,20,0.0%,0,700382982,Orb Wedding Centerpiece : Gloria GM-ORB ONLY \...,A,3,NaN,44%,071719

In [217]:
SEOGrades_fp=f"/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/Data/eRank_SEOGrades.csv"

 # Create or append to csv
if not os.path.isfile(SEOGrades_fp):
    df.to_csv(SEOGrades_fp, header='column_names')
else: # else it exists so append without writing the header
    df.to_csv(SEOGrades_fp, mode='a', header=False)

# Listing Details

In [223]:
path = r'/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData' # use your path
all_files = glob.glob(path + "/eRank_ListingDetails*.csv")

li = []

for filename in all_files:
    df = pd.read_csv(filename, index_col=None, header=0)
    first_split=filename.split('_', 3)[-1]
    date=first_split.split('.',1)[0]
    df['record_date']= date
    li.append(df)
    print(filename)
    
listing_details_df = pd.concat(li, axis=0, ignore_index=True, sort=True)

listing_details_df.head()

/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/eRank_ListingDetails_072219.csv
/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/CollectedData/eRank_ListingDetails_072119.csv

,#,DailyViews,Hearts per View,ImageCount,LastUpdated,ListingID,ListingTitle,MainImage,OriginallyCreated,Price,SKU,TagCount,TotalHearts,TotalViews,record_date
0,2,0.2,3.6%,4,2019-07-04,680069172,Wedding Centerpiece - Centerpiece - Engagement...,NaN,2019-03-26,41.99,NaN,13,1,28,072219
1,3,0.6,10.4%,4,2019-07-04,680071910,Wedding Centerpiece - Centerpiece - Engagement...,NaN,2019-03-26,28.99,NaN,13,7,67,072219
2,5,0.1,18.8%,6,2019-07-04,680077296,"Wedding Centerpiece Package, Centerpiece, Enga...",NaN,2019-03-26,28.99,NaN,13,3,16,072219
3,6,0.4,11.8%,5,2019-07-04,680079806,"Wedding Centerpiece Package, Centerpiece, Enga...",NaN,2019-03-26,30.99,NaN,12,6,51,072219
4,7,0.1,6.7%,5,2019-07-04,680082346,"Wedding Centerpiece Package, Centerpiece, Enga...",NaN,2019-03-26,42.99,NaN,13,1,15,072219

In [224]:
listing_details_df.drop(columns=['MainImage',"ListingTitle"],axis=1,inplace=True)

listing_details_df.head()

,#,DailyViews,Hearts per View,ImageCount,LastUpdated,ListingID,OriginallyCreated,Price,SKU,TagCount,TotalHearts,TotalViews,record_date
0,2,0.2,3.6%,4,2019-07-04,680069172,2019-03-26,41.99,NaN,13,1,28,072219
1,3,0.6,10.4%,4,2019-07-04,680071910,2019-03-26,28.99,NaN,13,7,67,072219
2,5,0.1,18.8%,6,2019-07-04,680077296,2019-03-26,28.99,NaN,13,3,16,072219
3,6,0.4,11.8%,5,2019-07-04,680079806,2019-03-26,30.99,NaN,12,6,51,072219
4,7,0.1,6.7%,5,2019-07-04,680082346,2019-03-26,42.99,NaN,13,1,15,072219

In [225]:
listing_details_fp=f"/Users/jessicaetchechury/Desktop/JEtchCreationsDashboard/Data/eRank_ListingDetails.csv"

 # Create or append to csv
if not os.path.isfile(listing_details_fp):
    listing_details_df.to_csv(listing_details_fp, header='column_names')
else: # else it exists so append without writing the header
    listing_details_df.to_csv(listing_details_fp, mode='a', header=False)